CREATE TABLE IF NOT EXISTS "library" (
    "call_num" NUMERIC(5, 1),
    "composer" TEXT,
    "title" TEXT,
    "ensemble" TEXT,
    "publisher" TEXT
);
INSERT INTO "library" VALUES
    (897.0,'Waldteufel','Les Patineurs Valses','Orchestra','Kalmus'),
    (1199.0,'Ravel','Pavane pour un Infante Defunte','Chamber Symphony','Baerenreiter'),
    (40.0,'Kreisler','Praeludium and Allegro','Chamber Symphony','Kalmus'),
    (345.0,'Kreisler','Caprice Viennois op. 2','Chamber Symphony','Kalmus'),
    (1158.0,'Kreisler','Tambourin Chinois, Op. 3','Chamber Symphony','Kalmus'),
    (1165.0,'SaintSaens','Concerto No. 2 for Piano and Orchestra','Chamber Symphony','Kalmus'),
    (1175.0,'VonWeber','Symphony No. 1 in C Major','Chamber Symphony','Kalmus'),
    (1162.0,'Beethoven','Congratulations Menuet','Chamber Symphony','Lucks'),
    (1181.0,'Beethoven','Grosse Fugue, Op. 133','Chamber Symphony','Lucks'),
    (1160.0,'Dvorak','Humoreske, Op. 101, no.7','Chamber Symphony','Lucks'),
    (1166.0,'Faure','Masques et Bergamasques','Chamber Symphony','Lucks'),
    (1237.0,'Faure','Elegie for Cello and Orchestra, Op. 24','Chamber Symphony','Lucks'),
    (1163.0,'Mozart','Three Marches, K. 408','Chamber Symphony','Lucks'),
    (1164.0,'Ravel','Le Tombeau de Couperin','Chamber Symphony','Lucks'),
    (1161.0,'Schubert','Marche Militaire, Op. 51, nos. 1 & 2','Chamber Symphony','Lucks'),
    (1159.0,'Mendelsshon','Auf Flugeln des Gesanges (On Wings of Song)','Chamber Symphony','Lucks'),
    (1234.0,'Walker','Crossing the Bar','Chamber Symphony and Womens Chorus','ECS'),
    (1235.0,'Walker','How Can I Keep From Singing?','Chamber Symphony and Womens Chorus','ECS'),
    (1236.0,'Walker','I Thank You, God','Chamber Symphony and Womens Chorus','ECS'),
    (1212.0,'Monti','Czardas for violin and orchestra','Chamber Symphony','Lucks'),
    (1272.0,'Bach','Symphony No. 3 in F Major Wq. 183/3','Chamber Symphony','Lucks'),
    (1185.0,'Grieg','Elegiac Melodies, Op. 34 Heart Wounds and Last Spring','Chamber Symphony','Lucks'),
    (1264.0,'Hindemith','Kammermusik No. 1, Op. 24, no. 1','Chamber Symphony','Lucks'),
    (1263.0,'Janacek','Concertino','Chamber Symphony','Lucks'),
    (1186.0,'Tchaikovsky','The Seasons: La Chasse (September: Hunting) Op.37, no. 9','Chamber Symphony','Lucks'),
    (1187.0,'Tchaikovsky','The Seasons: Barcarolle (June) Op. 37, no. 6','Chamber Symphony','Lucks'),
    (1188.0,'Tchaikovsky','The Seasons: Troika Op. 37, no. 11','Chamber Symphony','Lucks'),
    (1292.0,'Handel','Concerto grosso in g-minor','Concerto','Baerenreiter'),
    (1293.0,'Bizet','Carmen Suite no. 2','Orchestra','Lucks'),
    (1302.0,'Fucik','Entrance of the Gladiators','Orchestra','Lucks'),
    (1291.0,'Handel','Entrance of the Queen of Sheba','Orchestra','Lucks'),
    (1197.0,'Mozart','Concerto No. 4 for Violin and Orchestra KV 218 (D MAJOR)','Concerto','Baerenreiter'),
    (43.0,'Mozart','Concerto in D KV 466 Clarinet & Orchestra','Concerto','Baerenreiter'),
    (591.0,'Bach','Concerto #2 BWV 1047 Brandenburg','Concerto','Baerenreiter'),
    (283.0,'Bach','Concerto in A BMV 1055 Oboe D''Amore','Concerto','Baerenreiter'),
    (129.0,'Mozart','Concerto in G KV 503 paino','Concerto','Baerenreiter'),
    (134.0,'Mozart','Concerto in A KV 214 violin','Concerto','Baerenreiter'),
    (251.0,'Mozart','Concerto in KV 488 Piano','Concerto','Baerenreiter'),
    (313.0,'Mozart','Concerto in C minor KV 491 piano','Concerto','Baerenreiter'),
    (317.0,'Mozart','Concerto in G KV 313 Flute','Concerto','Baerenreiter'),
    (1023.0,'Mozart','Concerto in F Maj. For threee or two pianos KV242','Concerto','Baerenreiter'),
    (1070.0,'Mozart','Concerto in A major for Clarinet and Orchestra, K 622','Concerto','Baerenreiter'),
    (1072.0,'Mozart','Concerto in D minor for Piano and Orchestra, KV 466','Concerto','Baerenreiter'),
    (1120.0,'Mozart','Sinfonia Concertante in Eb Major KV.264 (320d)','Concerto','Baerenreiter'),
    (1123.0,'Mozart','Concerto in C major for flute, harp and orchestra, KV 299 (297c)','Concerto','Baerenreiter'),
    (1193.0,'Mozart','Concerto No. 21 in C Major for Piano & Orchestra','Concerto','Baerenreiter'),
    (1227.0,'Mozart','Concerto No. 2 in E-flat Major for Horn and Orchestra K. 417','Concerto','Baerenreiter'),
    (184.0,'Bach','Concerto #4 BWV 1049 Bradenburg','Concerto','Baerenreiter'),
    (406.0,'Mozart','Concerto KV 314 oboe','Concerto','Boosey and Hawkes'),
    (124.0,'Bach','Brandenburg Concerto #5 in D','Concerto','Breitkopf'),
    (173.0,'Bach','Concerto in D BWV 1043 2 violins','Concerto','Breitkopf'),
    (138.0,'Haydn','Concerto #1 in D cello','Concerto','Breitkopf'),
    (359.0,'Bach','Concerto #1 a minor Violin BWV 1041','Concerto','Breitkopf'),
    (1014.0,'Mendelsshon','Piano Concerto No. 1','Concerto','Broude Brothers'),
    (197.0,'Nielsen','Concerto Flute','Concerto','Dansk'),
    (9.0,'Nielsen','Concerto-Clarinet & Orchestra op.57','Concerto','Dansk'),
    (667.0,'Rachmaninoff','Rhapsodie on a Theme of Paganini piano','Concerto','Foley'),
    (665.0,'Mozart','Concerto KV453 piano','Concerto','International'),
    (140.0,'Bach','Concerto in D minor 2 violins','Concerto','Kalmus'),
    (174.0,'Bach','Concerto in F Brandenburg #2','Concerto','Kalmus'),
    (137.0,'Beethoven','Concerto No.4 Piano','Concerto','Kalmus'),
    (169.0,'Beethoven','Concerto No.3 op. 37 Piano','Concerto','Kalmus'),
    (365.0,'Beethoven','Concerto No.2 in Bb op. 19 piano','Concerto','Kalmus'),
    (469.0,'Beethoven','Concerto No.5 op. 73 op piano','Concerto','Kalmus'),
    (126.0,'Brahms','Concerto for Violin op. 77','Concerto','Kalmus'),
    (369.0,'Chopin','Concerto #2 op.21 piano','Concerto','Kalmus'),
    (477.0,'Grieg','Concerto op. 16 piano','Concerto','Kalmus'),
    (141.0,'Haydn','Concerto in D piano','Concerto','Kalmus'),
    (240.0,'Hummel','Concerto Trumpet','Concerto','Kalmus'),
    (1279.0,'Hummel','Trumpet Concerto (Practical edition by McAlister, 3rd edition, 2012)','Concerto','Kalmus'),
    (12.0,'Kabalevsky','Concerto Cello','Concerto','Kalmus'),
    (167.0,'Mendelsshon','Concerto op. 64 violin','Concerto','Kalmus'),
    (198.0,'Mozart','Concerto #5 Violin KV 219','Concerto','Kalmus'),
    (201.0,'Mozart','Concerto #3 Violin KV 216','Concerto','Kalmus'),
    (583.0,'Mozart','Concerto KV 622 for Clarinet','Concerto','Kalmus'),
    (533.0,'Popper','Hungarian Rhapsody cello op. 68','Concerto','Kalmus'),
    (319.0,'Quantz','Concerto in G Flute','Concerto','Kalmus'),
    (163.0,'Rachmaninoff','Concerto #2 op. 18 piano','Concerto','Kalmus'),
    (1233.0,'SaintSaens','Concerto No.1 for Cello and Orchestra in A Major, Op. 33','Concerto','Kalmus'),
    (115.0,'SaintSaens','Concerto #5 op. 103','Concerto','Kalmus'),
    (315.0,'Shostakovich','Concerto Cello','Concerto','Kalmus'),
    (236.0,'Tchaikovsky','Concerto #1 op. 23 Piano','Concerto','Kalmus'),
    (571.0,'Chopin','Concerto #1 op.11 piano','Concerto','Kalmus'),
    (444.0,'Vivaldi','Concerto in G minor Two Cellos','Concerto','Kunzelmann'),
    (36.0,'Beethoven','Concerto No.4 piano and orchestra','Concerto','Lucks'),
    (1121.0,'Bruch','Violin Concerto No. 2 in D Minor, Op.44','Concerto','Lucks'),
    (1192.0,'Chopin','Grand Polonaise Brillante and Andante Spianato for Piano and Orchestra, Op. 22','Concerto','Lucks'),
    (1108.0,'Elgar','Concerto in E minor','Concerto','Lucks'),
    (1009.0,'Lalo','Concerto, Cello','Concerto','Lucks'),
    (16.0,'Liszt','Piano concerto #1','Concerto','Lucks'),
    (133.0,'Mozart','Concerto #23 piano','Concerto','Lucks'),
    (1124.0,'Paganini','Violin Concerto No. 1 in D major','Concerto','Lucks'),
    (1289.0,'Schumann','Konzertstück, op. 86','Concerto','Lucks'),
    (156.0,'Vieuxtemps','Concerto #5 op. 37 violin','Concerto','Lucks'),
    (1024.0,'VonWeber','Bassoon concerto','Concerto','Lucks'),
    (1127.0,'VonWeber','Clarinet Concerto No. 1 in F minor, op.73','Concerto','Lucks'),
    (634.0,'Wieniawski','2nd Violin Concerto op.22','Concerto','Lucks'),
    (155.0,'Mozart','Concerto KV 482 piano','Concerto','Lucks'),
    (179.0,'Bach','Concerto #2 in E violin BWV 1042','Concerto','Lucks'),
    (168.0,'Beethoven','Concerto No.3 op. 37 Piano','Concerto','Lucks'),
    (1029.0,'Chaminade','Concertino for Flute and Orchestra','Concerto','Lucks'),
    (149.0,'Sibelius','Concerto op. 47 violin','Concerto','Lucks'),
    (1114.0,'Sammartini','Concerto Grosso Op.11 No.4','Concerto','Music Press Inc'),
    (1118.0,'Pergolesi','Concertino in mi bemolle','Concerto','Ricordi'),
    (166.0,'Vivaldi','Concerto in C piccolo','Concerto','Ricordi'),
    (664.0,'MacDowell','Concerto op. 23 piano','Concerto','Schirmer'),
    (666.0,'Rachmaninoff','Concerto #3op. 30 piano','Concerto','Schirmer'),
    (662.0,'SaintSaens','Concerto #3 op. 22 piano','Concerto','Schirmer'),
    (753.0,'Bach','Cembalo Concerto BWV 1053 in e min.','Concerto','Lucks'),
    (964.0,'Bach','Violin Concerto No. 1 a minor','Concerto','Lucks'),
    (783.0,'Beethoven','Violin Concerto op.61 D major','Concerto','Lucks'),
    (966.0,'Beethoven','Concerto No.2 for Piano','Concerto','Lucks'),
    (977.0,'Beethoven','Concerto No. 3 in c minor Piano','Concerto','Lucks'),
    (985.0,'Beethoven','Piano concerto #1 op.15','Concerto','Lucks'),
    (699.0,'Brahms','Concerto for Violin, Cello and Orch. Aminor op.102','Concerto','Lucks'),
    (864.0,'Brahms','Piano Concerto No. 1 d min Op. 15','Concerto','Lucks'),
    (689.0,'Dvorak','Cello Concerto in b minor op.104','Concerto','Lucks'),
    (948.0,'Grieg','Piano Concerto in a minor op.16','Concerto','Lucks'),
    (706.0,'Haydn','Trumpet Concerto','Concerto','Lucks'),
    (827.0,'Haydn','Cello Concerto in C hob. VIII b:1','Concerto','Lucks'),
    (738.0,'Mozart','Piano Concerto No. 28 (Concerto Rondo) op.28','Concerto','Lucks'),
    (802.0,'Mozart','Concerto Eb major piano KV 271','Concerto','Lucks'),
    (973.0,'Mozart','Concerto in A major, No. 5 for Violin & Orchestra','Concerto','Lucks'),
    (983.0,'Mozart','Piano Concerto #27 in Bb KV 595','Concerto','Lucks'),
    (924.0,'Prokofiev','Piano Concerto No.1 op 10','Concerto','Lucks'),
    (933.0,'Prokofiev','Piano Concerto No. 3 op 26','Concerto','Lucks'),
    (686.0,'Rachmaninoff','Piano Concerto #3 d min op. 30','Concerto','Lucks'),
    (1038.0,'Rusche','Dreaming the Ragwaltz Blues','Concerto','Lucks'),
    (845.0,'SaintSaens','Concerto No. 5 Piano Op.103','Concerto','Lucks'),
    (987.0,'SaintSaens','Violin Concerto No. 3 b minor','Concerto','Lucks'),
    (929.0,'Schumann','Piano concerto Op.54','Concerto','Lucks'),
    (843.0,'Stamitz','Viola Concerto Op. 1','Concerto','Lucks'),
    (85.0,'Tchaikovsky','Violin Concerto Op.35','Concerto','Lucks'),
    (824.0,'Vieuxtemps','Violin Concerto op.31','Concerto','Lucks'),
    (675.0,'VonWeber','Concerto for Piano op. 79 (Kunzertstuck)','Concerto','Lucks'),
    (832.0,'VonWeber','Concerto for Bassoon and Orchestra F major op.75','Concerto','Lucks'),
    (663.0,'Khatchturian','Concerto piano','Concerto','Leeds'),
    (1172.0,'Grainger','Irish Tune from County Derry','Wind Ensemble','Southern'),
    (486.0,'Berlin','White Christmas','Holiday','Berlin'),
    (540.0,'Elgar','Pomp and Circumstance','Holiday','Boosey and Hawkes'),
    (42.0,'Chase','Around the World at Christmas Time','Holiday','Hal Leonard'),
    (695.0,'Coots','Santa Claus is Coming to Town','Holiday','Hal Leonard'),
    (698.0,'Marks','Rudolph the Red-Nosed Reindeer','Holiday','Hal Leonard'),
    (147.0,'Marks','Rudolph the Red Nosed Reindeer','Holiday','Hal Leonard'),
    (34.0,'Handel','The Messiah Oratorio','Holiday','Kalmus'),
    (375.0,'Adam','O Holy Night','Holiday','Lucks'),
    (1006.0,'Holst','Christmas Day','Holiday','Lucks'),
    (45.0,'Mendelsshon','Hark! The Herald Angels Adeste Fidelis','Holiday','Lucks'),
    (1211.0,'Torme','The Christmas Song','Holiday','Lucks'),
    (1210.0,'VaughanWilliams','Fantasia on Christmas Carols','Holiday','Lucks'),
    (148.0,'Holcombe','Festive Sounds of Hanukah','Holiday','Lucks'),
    (44.0,'Handel','Angels We Have Heard /Joy to The world','Holiday','Lucks'),
    (90.0,'Handel','Hallelujah Chorus Messiah','Holiday','Lucks'),
    (1253.0,'Anderson','Sleigh Ride','Holiday','Belwin Mills'),
    (594.0,'Davis','Carol of the Drum','Holiday','Belwin Mills'),
    (252.0,'Handel','Messiah','Holiday','Novello'),
    (576.0,'Rutter','Nativity Carol','Holiday','Oxford'),
    (89.0,'Wilcocks','Five Christmas Carols','Holiday','Oxford'),
    (1031.0,'Rutter','Donkey Carol','Holiday','Oxford'),
    (250.0,'Haydn','Run Ye Sheperds Christmas Cantata','Holiday','Pressor'),
    (379.0,'Delameter','Christrmas Tide Overture','Holiday','Rubank'),
    (601.0,'Berlin','White Christmas (with chrous)','Holiday','Shawnee'),
    (610.0,'Elliott','Fum Fum Fum','Holiday','Wynn'),
    (1261.0,'Connick','When My Heart Finds Christmas','Holiday','Lucks'),
    (900.0,'Courtney','Musicological Journey the 12 Days of Christmas','Holiday','Lucks'),
    (746.0,'Custer','A Canadian Brass Christmas','Holiday','Lucks'),
    (794.0,'Davis','Traditions of Christmas','Holiday','Lucks'),
    (1203.0,'Lackey','Colors of Christmas','Holiday','Lucks'),
    (1224.0,'Lackey','Jingle Bells','Holiday','Lucks'),
    (1262.0,'Lackey','Christmas Medley for Two for solo voice, trpt, and alto sax','Holiday','Lucks'),
    (981.0,'Miller','Let There Be Peace On Earth','Holiday','Lucks'),
    (560.0,'Rose','Holiday for Strings','Holiday','Lucks'),
    (759.0,'Rutter','Bring a Torch Jeanette, Isabella','Holiday','Lucks'),
    (760.0,'Rutter','Christmas Lullaby','Holiday','Lucks'),
    (762.0,'Rutter','We Wish You A Merry Christmas','Holiday','Lucks'),
    (791.0,'Rutter','Candelight Carol','Holiday','Lucks'),
    (1200.0,'Rutter','Angel''s Carol','Holiday','Lucks'),
    (899.0,'Rutter','Very Best Time of the Year','Holiday','Lucks'),
    (703.0,'Rutter','Shepard''s Pipe Carol','Holiday','Lucks'),
    (937.0,'Smith','All is Well','Holiday','Lucks'),
    (793.0,'Torme','The Christmas Song in D Major','Holiday','Lucks'),
    (938.0,'Wilberg','I Saw three Ships','Holiday','Lucks'),
    (861.0,'Williams','Three Holiday Songs from Home Alone*','Holiday','Lucks'),
    (254.0,'Anderson','A Christmas Festival','Holiday','Belwin Mills'),
    (770.0,'McIntyre','Four English Carols','Holiday','Lucks'),
    (1299.0,'Silvestri','Polar Express','Holiday','Alfred'),
    (1297.0,'Schwartz','We Are Lights','Holiday','Grey Dog Music'),
    (1301.0,'Higgins','Christmas on Broadway','Holiday','Hal Leonard'),
    (1043.0,'Puccini','Manon Lescaut/Act III Intermezzo','Opera','Kalmus'),
    (1238.0,'Boccherini','Cello Concerto in B-flat Major','Orchestra','Lucks'),
    (1240.0,'Curtis','Balm in Gilead','Orchestra and choir','Lucks'),
    (1241.0,'Curtis','Changed My Name','Orchestra and choir','Lucks'),
    (1242.0,'Curtis','Ride On, King Jesus','Orchestra and choir','Lucks'),
    (1243.0,'Curtis','Struggle for Freedom','Orchestra and choir','Lucks'),
    (381.0,'Weinberger','Polka and Fugue','Orchestra','Associated'),
    (912.0,'Chopin','? Mazurka','Orchestra','Balakiren'),
    (194.0,'Handel','Royal Fireworks','Orchestra','Baerenreiter'),
    (290.0,'Bach','Sheep May Safely Graze','Orchestra','Boosey and Hawkes'),
    (257.0,'Britten','The Young Person''s guide to the Orchestra','Orchestra','Boosey and Hawkes'),
    (73.0,'Copland','Quiet City','Orchestra','Boosey and Hawkes'),
    (507.0,'Copland','Saturday Night Waltz rodeo','Orchestra','Boosey and Hawkes'),
    (64.0,'Copland','Fanfare for the Common Man','Orchestra','Boosey and Hawkes'),
    (354.0,'Copland','Hoe-Down Rodeo','Orchestra','Boosey and Hawkes'),
    (506.0,'Copland','Buckaroo Holiday Rodeo','Orchestra','Boosey and Hawkes'),
    (464.0,'Macdowell','Woodland Sketches op. 51','Orchestra','Boosey and Hawkes'),
    (183.0,'Franck','Psyche Et Eros','Orchestra','Boosey and Hawkes'),
    (353.0,'Copland','Four Dance Epsodes from Rodeo','Orchestra','Boosey and Hawkes'),
    (508.0,'Copland','Corral Nocturne Rodeo','Orchestra','Boosey and Hawkes'),
    (992.0,'Copland','Variations on A Shaker Melody from Appalachain Spring','Orchestra','Boosey and Hawkes'),
    (501.0,'Handel','The Faithful Shepherd Suite','Orchestra','Boosey and Hawkes'),
    (467.0,'Mozart','Exsultate Jubilate Motet','Orchestra','Breitkopf'),
    (336.0,'Wagner','Parsifal, Good Friday Spell ?','Orchestra','Breitkopf'),
    (139.0,'Tchaikovsky','Capriccio Italien op. 45','Orchestra','Breitkopf'),
    (998.0,'Beethoven','Turkish March from The Ruins of Athens','Orchestra','Broude Brothers'),
    (999.0,'Borodin','In The Steppes of Central Asia','Orchestra','Broude Brothers'),
    (1000.0,'Liadov','Eight Russian Folk Songs','Orchestra','Broude Brothers'),
    (88.0,'Bach','Toccata & Fugue in D minor','Orchestra','Broude Brothers'),
    (503.0,'Bach','Overture Suite #2 in B minor','Orchestra','Broude Brothers'),
    (268.0,'Bach','Toccata and Fugue Adagio','Orchestra','Broude Brothers'),
    (325.0,'Bach','Prelude, Choral& Fugue','Orchestra','Carl Fischer'),
    (1.0,'Bizet','Carmen- Suite #2','Orchestra','Carl Fischer'),
    (175.0,'Debussy','En Bateau Petite Suite','Orchestra','Carl Fischer'),
    (502.0,'Grieg','Lyric Suite','Orchestra','Carl Fischer'),
    (500.0,'Grieg','Sigurd Jorsalfar Suite','Orchestra','Carl Fischer'),
    (463.0,'Luigini','Ballet Egyptien','Orchestra','Carl Fischer'),
    (461.0,'SaintSaens','Algerian Suite op.60','Orchestra','Carl Fischer'),
    (455.0,'Tchaikovsky','Waltz of the Flowers Nutcracker','Orchestra','Carl Fischer'),
    (456.0,'Tchaikovsky','Trepak Nutcracker and Dase de la fee Drage','Orchestra','Carl Fischer'),
    (458.0,'Tchaikovsky','Chinese Dance and Dance of the Flutes Nutcracker','Orchestra','Carl Fischer'),
    (338.0,'Wagner','Tannhauser March','Orchestra','Carl Fischer'),
    (337.0,'Wagner','Good Friday Spell Parsifal','Orchestra','Carl Fischer'),
    (499.0,'Coates','London Every Day Suite','Orchestra','Chappell'),
    (510.0,'Debussy','Children''s Corner Suite','Orchestra','Durand'),
    (430.0,'Rameau','Dardanus Suite #1','Orchestra','Durand'),
    (431.0,'Rameau','Dardanus Suite #2','Orchestra','Durand'),
    (273.0,'SaintSaens','Bacchanale Samson and Deliah','Orchestra','Elkan Vogel'),
    (226.0,'Ravel','Pavane pour un Infante Defunte','Orchestra','Eschig'),
    (193.0,'Barber','Second Essay','Orchestra','Schirmer'),
    (511.0,'Faure','Pelleas et Melisande op.80','Orchestra','Hamelle'),
    (348.0,'Chabrier','Espana','Orchestra','Hampton'),
    (476.0,'Enesco','Rumanian Rhapsody op. 11 #1','Orchestra','Hampton'),
    (191.0,'Liszt','Les Preludes','Orchestra','Hampton'),
    (321.0,'Rimsky-Korsakov','Capriccio Espagnol','Orchestra','Hampton'),
    (171.0,'Smetana','Moldau','Orchestra','Hampton'),
    (130.0,'Gershwin','Rhapsody in Blue','Orchestra','Harms'),
    (818.0,'Anderson','Summer Skies','Orchestra','Kalmus'),
    (1040.0,'Anderson','Horse and Buggy','Orchestra','Kalmus'),
    (4.0,'Bizet','Carmen Suite #1','Orchestra','Kalmus'),
    (411.0,'Bruch','Fantasie op. 46','Orchestra','Kalmus'),
    (512.0,'Debussy','Nocturnes','Orchestra','Kalmus');
INSERT INTO "library" VALUES
    (165.0,'Debussy','Afternoon of a Faun','Orchestra','Kalmus'),
    (32.0,'Dvorak','Slavonic Dances 1-4','Orchestra','Kalmus'),
    (203.0,'Elgar','Chanson De Nuit op. 15 #1','Orchestra','Kalmus'),
    (202.0,'Elgar','Chanson De Martin op. 15 #2','Orchestra','Kalmus'),
    (993.0,'Holst','The Planets','Orchestra','Kalmus'),
    (443.0,'Mendelsshon','Nocturne,Midsummer Nights Dream','Orchestra','Kalmus'),
    (452.0,'Mendelsshon','Wedding March Midsummer Night''s Dream','Orchestra','Kalmus'),
    (453.0,'Mendelsshon','Scherzo Midsummer Night''s Dream','Orchestra','Kalmus'),
    (454.0,'Mendelsshon','Intermezzo Midsummer Night''s Dream','Orchestra','Kalmus'),
    (244.0,'Mozart','Ach, Ich Fuhl''s (Magic Flure)','Orchestra','Kalmus'),
    (245.0,'Mozart','non Mir dir (Don Giovanni)','Orchestra','Kalmus'),
    (121.0,'Ravel','Daphnes & Chloe 2nd suite','Orchestra','Kalmus'),
    (377.0,'Ravel','Ma Me''re L''oye (Mother Goose)','Orchestra','Kalmus'),
    (106.0,'Rimsky-Korsakov','Scheherazde','Orchestra','Kalmus'),
    (180.0,'Schubert','Overture in Italian Style','Orchestra','Kalmus'),
    (241.0,'Schubert','Magnificat','Orchestra','Kalmus'),
    (161.0,'Strauss','Ein Heldenleben','Orchestra','Kalmus'),
    (127.0,'Stravinsky','Firebird Suite(1919)','Orchestra','Kalmus'),
    (128.0,'Tchaikovsky','Nutcracker Suite','Orchestra','Kalmus'),
    (309.0,'Verdi','la Traviata Opera','Orchestra','Kalmus'),
    (447.0,'Verdi','Zitti, Zitti Rigoletto','Orchestra','Kalmus'),
    (448.0,'Verdi','Fuocco Di Gioia Othello','Orchestra','Kalmus'),
    (449.0,'Verdi','Va Pensiero Nabucco','Orchestra','Kalmus'),
    (451.0,'Verdi','Scorrendo Uniti Rigoletto','Orchestra','Kalmus'),
    (989.0,'Verdi','Requiem','Orchestra','Kalmus'),
    (253.0,'Verdi','The Four Seasons L''Inverno','Orchestra','Kalmus'),
    (87.0,'Verdi','Triumphal march from Aida','Orchestra','Kalmus'),
    (316.0,'Vivaldi','Gloria','Orchestra','Kalmus'),
    (123.0,'VonWeber','Invitation to the Dance','Orchestra','Kalmus'),
    (434.0,'VonWeber','Concertino Clarinet op. 26','Orchestra','Kalmus'),
    (70.0,'Beethoven','Absehuelieher Wo Eilst from Fidelio','Orchestra','Kalmus'),
    (246.0,'Faure','Pavane op. 50','Orchestra','Kalmus'),
    (304.0,'Gluck','Reigen Seliger Geister orpheus','Orchestra','Kalmus'),
    (993.0,'Holst','The Planets','Orchestra','Kalmus'),
    (265.0,'Rossini','pas De Six, From William Tell','Orchestra','Kalmus'),
    (485.0,'Tchaikovsky','Pas De Deux Nutcracker','Orchestra','Kalmus'),
    (158.0,'Bach','Cantata #142 Uns Ist Ein Kindeboren','Orchestra','Lucks'),
    (67.0,'Beethoven','Missa Solemis','Orchestra','Lucks'),
    (1020.0,'Boito','Mefistofele, prologue','Orchestra','Lucks'),
    (10.0,'Borodin','Prince Igor Polovestian Dances','Orchestra','Lucks'),
    (1014.0,'Gounod','Faust Ballet Music','Orchestra','Lucks'),
    (1025.0,'Grieg','Wedding Day at Troldhaugen','Orchestra','Lucks'),
    (172.0,'Mozart','Magic Flute Duet','Orchestra','Lucks'),
    (243.0,'Mozart','Mia Speranza a Dorata','Orchestra','Lucks'),
    (59.0,'Puccini','E Lucevan Le Stelle from Tosca','Orchestra','Lucks'),
    (228.0,'Puccini','Vissi D''Arte tosca','Orchestra','Lucks'),
    (404.0,'Rameau','Drei Balletstucke','Orchestra','Lucks'),
    (249.0,'Strauss','Laughing Song Die Fledermaus','Orchestra','Lucks'),
    (74.0,'Strauss','Don Juan','Orchestra','Lucks'),
    (318.0,'Stravinsky','Firebird Suite 1919','Orchestra','Lucks'),
    (1016.0,'Tchaikovsky','The Tempest','Orchestra','Lucks'),
    (62.0,'Verdi','La Donna E'' Mobile from Rigoletto','Orchestra','Lucks'),
    (157.0,'Verdi','Pace, pace Mio Dio La forza Del Destino','Orchestra','Lucks'),
    (1010.0,'Wagner','Wotan''s Farewell','Orchestra','Lucks'),
    (66.0,'Bizet','Jeux D''Enfants petite Suite op.22','Orchestra','Lucks'),
    (1028.0,'Delibes','Prelude and Mazurka from Coppelia','Orchestra','Lucks'),
    (291.0,'Bach','Sheep May Safely Graze','Orchestra','Peters'),
    (450.0,'Verdi','Te Deum #4','Orchestra','Peters'),
    (936.0,'Vivaldi','The Four Seasons','Orchestra','Ricordi'),
    (267.0,'Griffes','The White Peacock','Orchestra','Schirmer'),
    (227.0,'Menotti','Amahl & the Night Visitors-Shepard''s Dance','Orchestra','Schirmer'),
    (78.0,'Smetana','Three Dances form the Bartered Bride','Orchestra','Schirmer'),
    (834.0,'Brahms','Hungarian Dance 5,6,7','Orchestra','Schmeling'),
    (60.0,'Bartok','Rumanian folk Dances','Orchestra','Universal'),
    (308.0,'Lully','French Baroque Suite Le Bourgeois Gentilhom','Orchestra','Witmark'),
    (1037.0,'Bao-Yun','Happiness is Sun','Orchestra','Lucks'),
    (685.0,'Bartok','Romanian Folk Dances','Orchestra','Lucks'),
    (676.0,'Beethoven','Fantasie c-moll for Piano ,Choir , Orchestra op.80','Orchestra','Lucks'),
    (785.0,'Beethoven','Contradances','Orchestra','Lucks'),
    (763.0,'Berlioz','Dance of The Sylphs','Orchestra','Lucks'),
    (925.0,'Berlioz','Harold In Italy','Orchestra','Lucks'),
    (690.0,'Bizet','L[Arlesienne Suite No. 2','Orchestra','Lucks'),
    (875.0,'Bizet','L''Arlesienne Suite #2','Orchestra','Lucks'),
    (876.0,'Bizet','L''Arlesienne Suite No. 1','Orchestra','Lucks'),
    (709.0,'Brahms','Hungarian Dances #5&7','Orchestra','Lucks'),
    (739.0,'Brahms','Hungarian Dances Nos.5,6&7','Orchestra','Lucks'),
    (687.0,'Chabrier','Espana Rhapsody','Orchestra','Lucks'),
    (680.0,'Chausson','Poeme for Violin & orchestra','Orchestra','Lucks'),
    (708.0,'Chopin','Grand Fantasie op. 13','Orchestra','Lucks'),
    (740.0,'Chopin','Grand Fantasie op 13','Orchestra','Lucks'),
    (915.0,'De Falla','The Three Cornered Hat (complete)','Orchestra','Lucks'),
    (781.0,'Debussy','La Mer','Orchestra','Lucks'),
    (784.0,'Delibes','Valse de la Poupce et Czardas,Coppelia','Orchestra','Lucks'),
    (972.0,'Donizetti','O''Luce di quest anima','Orchestra','Lucks'),
    (737.0,'Dukas','La Per1''','Orchestra','Lucks'),
    (682.0,'Dvorak','Czech Suite op. 39','Orchestra','Lucks'),
    (871.0,'Dvorak','Serenade in d minor','Orchestra','Lucks'),
    (909.0,'Dvorak','Slavonic Dances op. 46 Nos. 5-8','Orchestra','Lucks'),
    (851.0,'Elgar','Enigma Variations Op.36','Orchestra','Lucks'),
    (892.0,'Faure','Pavane','Orchestra','Lucks'),
    (780.0,'Gliere','Russian Sailors Dance (from the Red Poppy)','Orchestra','Lucks'),
    (693.0,'Gounod','Romeo & Juliette','Orchestra','Lucks'),
    (715.0,'Gounod','Marionetten-Trauermarsch','Orchestra','Lucks'),
    (779.0,'Gounod','Ballet Music from Faust','Orchestra','Lucks'),
    (779.0,'Gounod','Margarete (Faust)','Orchestra','Lucks'),
    (772.0,'Grainger','The Immovable DO','Orchestra','Lucks'),
    (678.0,'Grieg','Peer Gynt Suite No. 1 op.46','Orchestra','Lucks'),
    (847.0,'Holst','Jupiter from The Planets','Orchestra','Lucks'),
    (829.0,'Horner','The Mask Of Zorro','Orchestra','Lucks'),
    (761.0,'Humperdinck','Hansel & Gretel Snadman''s Song, Evening Song, Drea','Orchestra','Lucks'),
    (862.0,'Humperdinck','Danse Duet from Hansel & Gretel','Orchestra','Lucks'),
    (863.0,'Humperdinck','Sandman''s Song, Dream Pantomine, ? From Han & Gret','Orchestra','Lucks'),
    (926.0,'Lackey','Fanfare (2002)','Orchestra','Lucks'),
    (776.0,'Lehar','Baqllsirenen from Merry Widow','Orchestra','Lucks'),
    (677.0,'Liszt','Les Preludes','Orchestra','Lucks'),
    (952.0,'Luck','God of Our Fathers/Holy, Holy. Holy','Orchestra','Lucks'),
    (707.0,'Mendelsshon','Rondo Brillant piano and orch.','Orchestra','Lucks'),
    (877.0,'Miller','Moonlight Serenade','Orchestra','Lucks'),
    (242.0,'Mozart','Una donna a Quindici Anni','Orchestra','Lucks'),
    (766.0,'Mozart','Magic Flute Paminas Aria No.17','Orchestra','Lucks'),
    (767.0,'Mozart','Die Hochzeit Jes Figaro','Orchestra','Lucks'),
    (868.0,'Mozart','Requiem KV. 626','Orchestra','Lucks'),
    (680.0,'Mussorgsky','Night on Bald Mountian','Orchestra','Lucks'),
    (927.0,'Mussorgsky','"Gopak" from the Fair At Sorochinski','Orchestra','Lucks'),
    (811.0,'Orff','Carmina Burana','Orchestra','Lucks'),
    (830.0,'Peck','The Thrill of the Orchestra','Orchestra','Lucks'),
    (887.0,'Puccini','An, Mario from Tosca','Orchestra','Lucks'),
    (919.0,'Puccini','Ah Mario From Tosca','Orchestra','Lucks'),
    (961.0,'Puccini','E'' Lucevan Le Stelle from Tosca','Orchestra','Lucks'),
    (692.0,'Ravel','Daphnis & Chole','Orchestra','Lucks'),
    (825.0,'Ravel','Ma Mere L''Oye (five Pieces for Orchestra)','Orchestra','Lucks'),
    (826.0,'Ravel','Rapsodie Espagnole','Orchestra','Lucks'),
    (893.0,'Respighi','Fontane di Roma','Orchestra','Lucks'),
    (879.0,'Rusche','Fanfare for the Millennium','Orchestra','Lucks'),
    (741.0,'Rutter','Go Tell It on The Mountain','Orchestra','Lucks'),
    (742.0,'Rutter','Jesus Child','Orchestra','Lucks'),
    (743.0,'Rutter','Star Carol','Orchestra','Lucks'),
    (744.0,'Rutter','Mary''s Lullaby','Orchestra','Lucks'),
    (681.0,'SaintSaens','Introduction and Rondo Carpiccioso','Orchestra','Lucks'),
    (679.0,'SaintSaens','Dance Macabe op. 40','Orchestra','Lucks'),
    (696.0,'Schubert','Ave Maria','Orchestra','Lucks'),
    (828.0,'Schubert','An die Musik','Orchestra','Lucks'),
    (806.0,'Sibelius','Finlandia op.26','Orchestra','Lucks'),
    (988.0,'Sibelius','Karelia Suite','Orchestra','Lucks'),
    (684.0,'Smetana','"Sarka"','Orchestra','Lucks'),
    (791.0,'Smetana','3 Dances from the Barterd Bride','Orchestra','Lucks'),
    (959.0,'Smetana','Ma Vlast #4 From Bohemia''s Forest and Meadows','Orchestra','Lucks'),
    (970.0,'Smetana','Vysehrad','Orchestra','Lucks'),
    (971.0,'Smetana','Blanik (from the Moldau)','Orchestra','Lucks'),
    (881.0,'Strauss','Acelleration Waltz','Orchestra','Lucks'),
    (786.0,'Strauss','Autzan Tanze Polka ?','Orchestra','Lucks'),
    (817.0,'Strauss','Wine, Women & Song','Orchestra','Lucks'),
    (913.0,'Strauss','Fata Morgana op. 330','Orchestra','Lucks'),
    (881.0,'Strauss','Fledermaus Overture','Orchestra','Lucks'),
    (881.0,'Strauss','An der schonen blauen Donau/Blue Danube','Orchestra','Lucks'),
    (881.0,'Strauss','Champagner Polka','Orchestra','Lucks'),
    (881.0,'Strauss','Erinnerungsgalopp','Orchestra','Lucks'),
    (881.0,'Strauss','Radetzky-Marsch','Orchestra','Lucks'),
    (923.0,'Strauss','Death & Transfiguration','Orchestra','Lucks'),
    (823.0,'Strauss','Till Eulenspiegles (Merry Pranks)','Orchestra','Lucks'),
    (768.0,'Stravinsky','Pertriuchka','Orchestra','Lucks'),
    (805.0,'Tchaikovsky','Polonaise from "Eugene Onegin"','Orchestra','Lucks'),
    (719.0,'Tchaikovsky','Trancesca On Rimni','Orchestra','Lucks'),
    (720.0,'Tchaikovsky','Serenade Melancholigve Op. 26','Orchestra','Lucks'),
    (722.0,'Tchaikovsky','Souvenir D''un Lieu Cher III Melodie','Orchestra','Lucks'),
    (733.0,'Tchaikovsky','Souvenir D''un Lieu Cher I Meditation','Orchestra','Lucks'),
    (734.0,'Tchaikovsky','Souvenir D''in Lieu Cher II Scherzo','Orchestra','Lucks'),
    (735.0,'Tchaikovsky','Valse-Scherzo op. 34','Orchestra','Lucks'),
    (792.0,'Tchaikovsky','Waltz of the Snowflakes','Orchestra','Lucks'),
    (821.0,'Tchaikovsky','Scene Finale #29 Swan Lake','Orchestra','Lucks'),
    (833.0,'Tchaikovsky','Sleeping Beauty Suite op. 66','Orchestra','Lucks'),
    (911.0,'Tchaikovsky','Le Chocolat From Nutcracker','Orchestra','Lucks'),
    (979.0,'Tchaikovsky','Scene #6 from the Nutcracker','Orchestra','Lucks'),
    (980.0,'Tchaikovsky','En''tracte from The Sleeping Beauty No.18','Orchestra','Lucks'),
    (700.0,'Tchaikovsky','Swan Lake Suite','Orchestra','Lucks'),
    (758.0,'VaughanWilliams','Fantasia on Greensleeves','Orchestra','Lucks'),
    (866.0,'Verdi','Brinoisi From La Traviata','Orchestra','Lucks'),
    (867.0,'Verdi','Boua Figlid O? Amore riolletto No. 12 Quartet','Orchestra','Lucks'),
    (901.0,'Verdi','I Vespri Siciliani Overtrue (Sinfonia)','Orchestra','Lucks'),
    (902.0,'Verdi','Anvil Chorus (IL Travtore)','Orchestra','Lucks'),
    (903.0,'Verdi','Zitti-Zitti form Rigolletto','Orchestra','Lucks'),
    (904.0,'Verdi','Selna(?) Aria e Miserere (d''amor sull'' rose) IL Tr','Orchestra','Lucks'),
    (906.0,'Verdi','En tu Che maccainui (The Masked Ball)','Orchestra','Lucks'),
    (906.0,'Verdi','L''  Onore ladri/Honor Monolgue (Falstaff)','Orchestra','Lucks'),
    (908.0,'Verdi','Stabat Mater','Orchestra','Lucks'),
    (910.0,'Verdi','Finale Act II','Orchestra','Lucks'),
    (911.0,'Verdi','Valentin''s Prayer from Faust','Orchestra','Lucks'),
    (917.0,'Verdi','"Pace Pace" form la Forza del Destino','Orchestra','Lucks'),
    (918.0,'Verdi','Simpre Libra, Di Provenza, Parigi o Cara','Orchestra','Lucks'),
    (683.0,'Wagner','Prelude & Love Death from Tristan and Isolde','Orchestra','Lucks'),
    (872.0,'Wagner','Siefreied''s Rheinfahrt','Orchestra','Lucks'),
    (704.0,'Waldteufel','Roses de Noel','Orchestra','Lucks'),
    (773.0,'Walton','Partitia for Orchestra','Orchestra','Lucks'),
    (645.0,'Schubert','Magnificat','Orchestra','Arista'),
    (1183.0,'Bach','Suite No.3 in D (Overture D-Dur BWV 1068)','Orchestra','Baerenreiter'),
    (1110.0,'Haydn','Lord Nelson Mass','Orchestra','Baerenreiter'),
    (1148.0,'Vivaldi','Four Seasons','Orchestra','Baerenreiter'),
    (636.0,'Offenbach','Orpheus in the Underworld','Orchestra','Boosey and Hawkes'),
    (606.0,'Britten','Soirees Musicales','Orchestra','Boosey and Hawkes'),
    (1112.0,'Stravinsky','Suite de Pulcinella','Orchestra','Boosey and Hawkes'),
    (591.0,'Brahms','Variations on a Theme by Haydn','Orchestra','Breitkopf'),
    (604.0,'Bach','Suite No.3 in D','Orchestra','Breitkopf'),
    (655.0,'Sibelius','Findlandia','Orchestra','Breitkopf'),
    (595.0,'Bizet','L''Arlesienne Suite #2 Minuet & Farrandoler','Orchestra','Carl Fischer'),
    (562.0,'Glazunov','Autumn & Winter (The Seasons)','Orchestra','Carl Fischer'),
    (611.0,'Massenet','Scenes Alsaciennes (part 2)','Orchestra','Carl Fischer'),
    (558.0,'Mendelsshon','Intermezzo and Nocturne','Orchestra','Carl Fischer'),
    (558.0,'Mendelsshon','Nocturne and Intermezzo','Orchestra','Carl Fischer'),
    (551.0,'Rimsky-Korsakov','Scheherazade','Orchestra','Carl Fischer'),
    (609.0,'Rimsky-Korsakov','Scheherazade (movt 4)','Orchestra','Carl Fischer'),
    (608.0,'Rimsky-Korsakov','Scheherazade Movt. 1','Orchestra','Carl Fischer'),
    (459.0,'Tchaikovsky','Arabian Dande March Nutcracker','Orchestra','Carl Fischer'),
    (552.0,'Rimsky-Korsakov','Scheherazade (3rd movt.)','Orchestra','Carl Fischer'),
    (593.0,'Coates','The Three Elizabeth Suite','Orchestra','Chappell'),
    (592.0,'Debussy','La Boite a Joujoux','Orchestra','Durand'),
    (641.0,'Borodin','On the Steppes of Central Asia','Orchestra','Eulenburg'),
    (642.0,'Strauss','Wine, Women and Song','Orchestra','Eulenburg'),
    (607.0,'Britten','Matinees Musicales','Orchestra','Boosey and Hawkes'),
    (1073.0,'Haydn','Sinfonia No. 94','Orchestra','Haydn Mozart Press'),
    (513.0,'Bach','Suite No.3 in D','Orchestra','Kalmus'),
    (1115.0,'Bach','Sinfonia in Bb Major Op.18 No.2','Orchestra','Kalmus'),
    (599.0,'Berlioz','Hungarian march (Damnation of Faust)','Orchestra','Kalmus'),
    (653.0,'Bizet','Intermezzi from Carmen','Orchestra','Kalmus'),
    (617.0,'Dukas','The Sorcere''s Apprentice','Orchestra','Kalmus'),
    (650.0,'Holst','Christmas Day','Orchestra','Kalmus'),
    (1046.0,'Leoncavallo','Pagliacci - Intermezzo','Orchestra','Kalmus'),
    (1150.0,'Sibelius','Pelleas and Melisande, op.46','Orchestra','Kalmus'),
    (1153.0,'Strauss','Don Quixote','Orchestra','Kalmus'),
    (534.0,'Strauss','MacBeth (TonePoem) op. 23','Orchestra','Kalmus'),
    (509.0,'Wagner','Siegfried Idyll','Orchestra','Kalmus'),
    (1128.0,'Bach','Ave Maria','Orchestra','Lucks'),
    (1065.0,'Berlioz','Damnation of Faust','Orchestra','Lucks'),
    (582.0,'Brahms','Serenade No. 1 in D','Orchestra','Lucks'),
    (1119.0,'Cherubini','Sinfonia in D Major','Orchestra','Lucks'),
    (1071.0,'Chopin','Polonaise Militaire','Orchestra','Lucks'),
    (1055.0,'Chopin','Mazurka No. 7','Orchestra','Lucks'),
    (1125.0,'Dvorak','Symphonic Variations op. 78','Orchestra','Lucks'),
    (1067.0,'Dvorak','Mein Heim','Orchestra','Lucks'),
    (1052.0,'Humperdinck','Witch''s Dance from Hansel and Gretel','Orchestra','Lucks'),
    (1051.0,'Liszt','Mephisto Waltz No. 1','Orchestra','Lucks'),
    (1045.0,'Mascagni','Cavalleria Rusticana Intermezzo','Orchestra','Lucks'),
    (1154.0,'Mendelsshon','Midsummer Night''s Dream - Nocturne','Orchestra','Lucks'),
    (1069.0,'Mozart','Idomeneo Ballet Music','Orchestra','Lucks'),
    (1075.0,'Mozart','Per pieta, non ricercate, K.420','Orchestra','Lucks'),
    (1141.0,'Mozart','Finch'' han dal vino calda la testa from Don Giovanni','Orchestra','Lucks'),
    (1142.0,'Mozart','Der Vogelfanger bin ich ja'' from The Magic Flute','Orchestra','Lucks'),
    (1144.0,'Mozart','Vedro mentr''io sospiro from The Marriage of Figaro','Orchestra','Lucks'),
    (1157.0,'Offenbach','Tales of Hoffman: Intermezzo&Barcarolle','Orchestra','Lucks'),
    (1063.0,'Offenbach','Tales of Hoffman: Barcarolle','Orchestra','Lucks'),
    (597.0,'Purcell','Trumpet Prelude','Orchestra','Lucks'),
    (1060.0,'Sibelius','Pelleas and Melisande','Orchestra','Lucks'),
    (1064.0,'Sibelius','Finlandia','Orchestra','Lucks'),
    (1050.0,'Verdi','La Traviata, Prelude to Act III','Orchestra','Lucks'),
    (1048.0,'Wagner','Lohengrin, Prelude ot Act I','Orchestra','Lucks'),
    (1049.0,'Wagner','Lohengrin, Bridal Chorus','Orchestra','Lucks'),
    (1074.0,'Beethoven','Romances for Violin and Orchestra Op. 40, Op.50(G major and F major)','Concerto','Lucks'),
    (578.0,'Glazunov','Winter (The Seasons)','Orchestra','Lucks'),
    (1054.0,'Wagner','Ride of the Valkries','Orchestra','Masters'),
    (614.0,'Ponchielli','Dance of the Hour','Orchestra','Pepper'),
    (635.0,'Verdi','Requiem','Orchestra','Peters');
INSERT INTO "library" VALUES
    (613.0,'Godard','Adagio Pathetique','Orchestra','Schirmer'),
    (652.0,'Creston','Invocation and Dance','Orchestra','Schirmer'),
    (596.0,'VaughanWilliams','March of the Kitchen Utensils','Orchestra','Schirmer'),
    (654.0,'Bach','Prelude and Fugue','Orchestra','Witmark'),
    (514.0,'Puccini','Un Bel Di Madame butterfly','Orchestra','Lucks'),
    (255.0,'Bizet','L''Arlesienne Suite#2 Farandole','Orchestra','Lucks'),
    (1145.0,'Lehar','No.7 Introduction, Tanz und Vilja - Lied','Orchestra','Lucks'),
    (736.0,'Strauss','Also Sprach Zarathrustra','Orchestra','Lucks'),
    (669.0,'Sullivan','I Have a Song Mikado','Opera','Lucks'),
    (670.0,'Sullivan','Poor Wandering One Mikado','Opera','Lucks'),
    (671.0,'Sullivan','Were You Not Mikado','Opera','Lucks'),
    (1057.0,'Verdi','La Traviata, Act I, Balzer Duet - Introduction (Act I)','Opera','Lucks'),
    (643.0,'Wagner','Ride of Valkyries','Orchestra','Lucks'),
    (991.0,'Williams','Suite from J.F.K.','Orchestra','Hal Leonard'),
    (721.0,'Tchaikovsky','Marche Slave','Orchestra','Lucks'),
    (672.0,'Spohr','Quartet-concert String Quartet op. 131','String Quartet','Kalmus'),
    (498.0,'Weber','Oberon Overture','Overture','Breitkopf'),
    (135.0,'Bach','Overture ton Temistocle','Overture','Lucks'),
    (205.0,'Humperdinck','Hansel & Gretel Prelude','Overture','Associated'),
    (207.0,'Smetana','The Bartered Bride Overture','Overture','Associated'),
    (229.0,'Wagner','Die Meistersinger Act 3 Dance, Procession','Overture','Associated'),
    (1134.0,'Mozart','Overture to the Abduction from the Seraglio, KV 384','Overture','Baerenreiter'),
    (1281.0,'Mozart','Don Giovanni Overture (BARENREITER)','Overture','Baerenreiter'),
    (1206.0,'Mendelsshon','Overture to Midsummer Night''s Dream','Overture','Baerenreiter'),
    (495.0,'Copland','An Outdoor Overture','Overture','Boosey and Hawkes'),
    (208.0,'Mozart','The Shepard King Overture','Overture','Boosey and Hawkes'),
    (523.0,'Nicolai','The Merry Wives of Windsor Overture','Overture','Boosey and Hawkes'),
    (418.0,'Rossini','Semiramide Overture','Overture','Boosey and Hawkes'),
    (517.0,'Schubert','Rosamund Overture','Overture','Boosey and Hawkes'),
    (421.0,'Beethoven','Coriolanus Overture','Overture','Boosey and Hawkes'),
    (519.0,'Wagner','Introductioj to Act 3 Lohengrin','Overture','Breitkopf'),
    (468.0,'Beethoven','Egmont Overture','Overture','Breitkopf'),
    (489.0,'Berlioz','Roman Carnival Overture','Overture','Breitkopf'),
    (69.0,'Mozart','The Marriage of Figaro(lle Nozze di figaro)','Overture','Breitkopf'),
    (480.0,'Rossini','Barber of Seville Overture','Overture','Breitkopf'),
    (997.0,'Beethoven','Prometheus Overture','Overture','Breitkopf'),
    (493.0,'Rossini','L Gazza Ladra Overture','Overture','Breitkopf'),
    (206.0,'Gluck','Ipheginia in Aulis overture','Overture','Breitkopf'),
    (541.0,'Glinka','Russlan and Ludmilla Overture','Overture','Carl Fischer'),
    (526.0,'Wagner','Lohengrin Prelude','Overture','Carl Fischer'),
    (580.0,'Mendelsshon','Fingal''s Cave Overture','Overture','Carl Fischer'),
    (538.0,'Beethoven','Egmont Overture op. 84','Overture','Carl Fischer'),
    (487.0,'Nicolai','The Merry Wives of Windsor Overture','Overture','Carl Fischer'),
    (516.0,'Schubert','Rosamund Overture','Overture','Carl Fischer'),
    (417.0,'Strauss','Die Fledermaus op. 362 (the Bat) Overture','Overture','Carl Fischer'),
    (460.0,'Tchaikovsky','Overture Nutcracker','Overture','Carl Fischer'),
    (520.0,'Wagner','Die Meistersinger Overture','Overture','Carl Fischer'),
    (521.0,'Wagner','Rienzi Overture','Overture','Carl Fischer'),
    (527.0,'Wagner','Introduction to Act 3 Lohengrin','Overture','Carl Fischer'),
    (271.0,'Coates','The Merrymakers Overture','Overture','Chappell'),
    (539.0,'Bennet','The Feast of Lanterns Overture','Overture','Ditson'),
    (524.0,'SaintSaens','Le Deluge Prelude op. 45','Overture','Durand'),
    (644.0,'Rimsky-Korsakov','Russian Easter Overture','Overture','Eulenburg'),
    (35.0,'Beethoven','Leonore Op. 72a overture #3','Overture','Hampton'),
    (553.0,'Brahms','Academic Festival Overture','Overture','Hampton'),
    (420.0,'Mozart','Don Giovanni Overture','Overture','Hampton'),
    (484.0,'Purcell','The Rival Sisters','Overture','Hampton'),
    (623.0,'Wagner','Prelude & Love Death (Tristan & Isolde)','Overture','Hampton'),
    (37.0,'Beethoven','Coriolan Overture op. 62','Overture','Henle'),
    (429.0,'Arriaga','Los Esclavos Felices Overture','Overture','Kalmus'),
    (371.0,'Beethoven','Die Wiehe Des Hauses Overture op.124','Overture','Kalmus'),
    (528.0,'Brahms','Academic Festival Overture','Overture','Kalmus'),
    (555.0,'Brahms','Tragic Overture op.81','Overture','Kalmus'),
    (355.0,'Dvorak','Carnival Overture','Overture','Kalmus'),
    (312.0,'Glinka','Russlan & Ludmilla Overture','Overture','Kalmus'),
    (160.0,'Mendelsshon','Ruy Blas Overture','Overture','Kalmus'),
    (356.0,'Mendelsshon','Fingal''s Cave Overture op.26','Overture','Kalmus'),
    (357.0,'Mozart','The Magic Flute Overture KV. 620','Overture','Kalmus'),
    (422.0,'Mozart','The Impresario KV. 486','Overture','Kalmus'),
    (479.0,'Mozart','Magic Flute Overture','Overture','Kalmus'),
    (196.0,'Mussorgsky','Kohovantchina Introduction','Overture','Kalmus'),
    (572.0,'Offenbach','Orpheus in hades Overture','Overture','Kalmus'),
    (21.0,'Rossini','William Tell Overture','Overture','Kalmus'),
    (109.0,'Rossini','Italian in Algiers Overture','Overture','Kalmus'),
    (414.0,'Rossini','IL Signor Bruschino','Overture','Kalmus'),
    (488.0,'Rossini','La Scala Di Seta Overture','Overture','Kalmus'),
    (494.0,'Rossini','La Gazza Ladra overture','Overture','Kalmus'),
    (525.0,'Schubert','Rosamunde Overture','Overture','Kalmus'),
    (416.0,'Sullivan','The Pirates of Penzance Overture','Overture','Kalmus'),
    (470.0,'Suppe','Light Cavalry overture','Overture','Kalmus'),
    (491.0,'Thomas','Mignon Overture','Overture','Kalmus'),
    (238.0,'Tchaikovsky','Romeo and Juliet Overture','Overture','Kalmus'),
    (478.0,'Tchaikovsky','Romeo and Juliet Overture','Overture','Kalmus'),
    (492.0,'Wagner','Parsifal Prelude','Overture','Kalmus'),
    (119.0,'Wagner','die Meistersinger Overture','Overture','Kalmus'),
    (640.0,'Weber','Der Freischutz Overture','Overture','Kalmus'),
    (1109.0,'VaughanWilliams','The Wasps Overture','Overture','Lucks'),
    (496.0,'Beethoven','Fidelio Overture','Overture','Lucks'),
    (1044.0,'Mendelsshon','A Midsummer Night''s Dream - Overture','Overture','Lucks'),
    (1017.0,'Mozart','Titus Overture, La Clamenza di Tito','Overture','Lucks'),
    (1014.0,'Rimsky-Korsakov','May Night Overture','Overture','Lucks'),
    (1126.0,'Schumann','Scherzo and Finale, op.52','Overture','Lucks'),
    (1246.0,'Strauss','Die Fledermaus op. 362 Overture','Overture','Lucks'),
    (994.0,'Suppe','Morning, Noon and Night in Vienna Overture','Overture','Lucks'),
    (195.0,'Verdi','La Traviata Prelude Act I','Overture','Lucks'),
    (374.0,'Verdi','La Forza Del Destino Overture','Overture','Lucks'),
    (22.0,'Wagner','The Flying Dutchman Overture','Overture','Lucks'),
    (1122.0,'Wagner','Tannhauser','Overture','Lucks'),
    (482.0,'Kabalevsky','Colas Breugon Overture','Overture','Lucks'),
    (1042.0,'Mendelsshon','Overture to Midsummer Night''s Dream','Overture','Lucks'),
    (192.0,'Shostakovich','Festive Overture','Overture','Lucks'),
    (204.0,'Offenbach','La Vie Perisienne Overture','Overture','Belwin Mills'),
    (529.0,'Beethoven','Creatures of Promethus Overture','Overture','Odeon'),
    (235.0,'Barber','School for Scandal Overture','Overture','Schirmer'),
    (497.0,'WolfFerrari','Secrets of Suzanne Overture','Overture','Schirmer'),
    (483.0,'Mozart','Cosi Fan Tutte Overture','Overture','Southern'),
    (570.0,'Tchaikovsky','1812 Overture','Overture','Kalmus'),
    (874.0,'Bach','Overture in C Major BWV 1006','Overture','Lucks'),
    (865.0,'Beethoven','Consecration of the House Overture','Overture','Lucks'),
    (718.0,'Berlioz','Corsar Overture','Overture','Lucks'),
    (819.0,'Handel','Overtrue to Teseo (?)','Overture','Lucks'),
    (820.0,'Handel','Overture To IL ?','Overture','Lucks'),
    (976.0,'Mozart','Overtrue from the Baber of Seville','Overture','Lucks'),
    (792.0,'Rimsky-Korsakov','Russian Easter Overture','Overture','Lucks'),
    (797.0,'Rimsky-Korsakov','Russian Easter Overture op.36','Overture','Lucks'),
    (705.0,'Rossini','Overture','Overture','Lucks'),
    (844.0,'Rossini','Die Italienerin In Algier Overture','Overture','Lucks'),
    (481.0,'Rossini','Barber of Seville Italian in Algiers La Gaza','Overture','Lucks'),
    (962.0,'Schumann','Manfred Overture op.115','Overture','Lucks'),
    (940.0,'Tayler','Genesis Overture','Overture','Lucks'),
    (986.0,'VonWeber','Der Freischutz Overture','Overture','Lucks'),
    (639.0,'Weber','Euryanthe Overture','Overture','Lucks'),
    (764.0,'Zork','Anniverary Overture','Overture','Lucks'),
    (274.0,'Sousa','Semper Fidelis March','Patriotic','Carl Fischer'),
    (150.0,'Smith','Star Spangled Banner','Patriotic','Schirmer'),
    (286.0,'Sousa','Washington Post March','Patriotic','Carl Fischer'),
    (222.0,'Powell','Natchez on the Hill','Patriotic','Schirmer'),
    (428.0,'Sousa','El Capitan March','Patriotic','Kalmus'),
    (136.0,'Sousa','The Liberty Bell','Patriotic','Kalmus'),
    (575.0,'Bagley','National Emblem March','Patriotic','Lucks'),
    (320.0,'Thompson','Salute to the Morris','Patriotic','Manuscript'),
    (65.0,'Smith','Star Spangled Banner','Patriotic','Belwin Mills'),
    (287.0,'Shea','Notre Dame Victory March','Patriotic','Morris'),
    (223.0,'Gottschalk','Souvenir de Porto Rico','Patriotic','Pressor'),
    (1030.0,'Jacobs','This is my Country','Patriotic','Shawnee'),
    (565.0,'Ringwald','Battle Hymn of the Republic','Patriotic','Shawnee'),
    (281.0,'Sousa','Stars & Stripes Forever March','Patriotic','Lucks'),
    (159.0,'Greenwood','God Bless the U.S.A.','Patriotic','Hal Leonard'),
    (56.0,'Smith','Star Spangled Banner, America the Beautiful','Patriotic','Lucks'),
    (1221.0,'Milhaud','Concerto pour marimba (et vibraphone) et orchestre*','Concerto','Durand'),
    (230.0,'Williams','Star Wars','Pops','2oth Century'),
    (1178.0,'Handel','Hallelujah from Messiah: A Soulful Celebration','Pops','Alfred'),
    (1176.0,'Porter','Cole Porter Salute','Pops','Alfred'),
    (332.0,'Strauss','Blue Danube Waltz','Pops','Barnhouse'),
    (1013.0,'Beckel','Amazing Grace','Pops','Beckel'),
    (1011.0,'Anderson','Leroy Anderson Favorites','Pops','Belwin Mills'),
    (25.0,'Ellington','A Medley','Pops','Belwin Mills'),
    (438.0,'Joplin','Sun Flower Slow Drag','Pops','Belwin Mills'),
    (437.0,'Joplin','Ragtime Dance','Pops','Belwin Mills'),
    (1245.0,'Lopez','Whitney Houston Tribute','Pops','Belwin Mills'),
    (1041.0,'Shore','The Lord of The Rings/The Two Towers','Pops','Belwin Mills'),
    (530.0,'Anderson','Bugler''s Holiday','Pops','Belwin Mills'),
    (531.0,'Anderson','Jazz Pizzicato','Pops','Belwin Mills'),
    (532.0,'Anderson','A Trumpeter''s Lullaby','Pops','Belwin Mills'),
    (536.0,'Gould','American Salute','Pops','Belwin Mills'),
    (247.0,'Sousa','Annie','Pops','Big 3'),
    (305.0,'Bejamin','Jamaican Rumba','Pops','Boosey and Hawkes'),
    (1143.0,'Bernstein','West Side Story (Selections for Orchestra)','Pops','Boosey and Hawkes'),
    (224.0,'Copland','Our Town','Pops','Boosey and Hawkes'),
    (388.0,'Delibes','Pizzicato','Pops','Boosey and Hawkes'),
    (177.0,'Strauss','Thunder & Lighting Polka','Pops','Boosey and Hawkes'),
    (574.0,'VaughanWilliams','English folk songs','Pops','Boosey and Hawkes'),
    (295.0,'Churchill','Snow White Fantasy','Pops','Bourne'),
    (302.0,'Strauss','Persian march op 289','Pops','Broadcast'),
    (585.0,'VonTilzer','Take Me Out to the Ball Game','Pops','Broadway'),
    (712.0,'Gould','Soft Shoe Gavotte','Pops','C and G Music'),
    (400.0,'Beethoven','Contra Dances No.1','Pops','Carl Fischer'),
    (352.0,'Bizet','Carmen Suite#1','Pops','Carl Fischer'),
    (346.0,'Boccherini','Celebrated Minuet','Pops','Carl Fischer'),
    (632.0,'Braga','Angel''s serenade','Pops','Carl Fischer'),
    (392.0,'Brahms','Hungarian Dances #5, #6','Pops','Carl Fischer'),
    (61.0,'Brahms','Hungarian Dance #5','Pops','Carl Fischer'),
    (391.0,'Brahms','Hungarian Dances #7, #8','Pops','Carl Fischer'),
    (347.0,'Chabrier','Espana Rhapsody','Pops','Carl Fischer'),
    (618.0,'Delibes','Entracte and Valse (coppelia)','Pops','Carl Fischer'),
    (349.0,'Delibes','Passapied','Pops','Carl Fischer'),
    (620.0,'Dinicu','Hora Staccato','Pops','Carl Fischer'),
    (589.0,'Dvorak','Two Slavonic Dances','Pops','Carl Fischer'),
    (341.0,'Dvorak','Two Slavonic Dances','Pops','Carl Fischer'),
    (303.0,'Fucik','Entry of the Gladiators op. 68','Pops','Carl Fischer'),
    (402.0,'Gould','Corn Cob Dance','Pops','Carl Fischer'),
    (297.0,'Grieg','Norwegian Dance','Pops','Carl Fischer'),
    (261.0,'Grieg','Bridal Procession','Pops','Carl Fischer'),
    (632.0,'Handel','Largo','Pops','Carl Fischer'),
    (542.0,'Haydn','Toy Symphony','Pops','Carl Fischer'),
    (380.0,'Humperdinck','Hansel and Gretel Selection','Pops','Carl Fischer'),
    (345.0,'Kreisler','Caprice Viennois op. 2','Pops','Carl Fischer'),
    (616.0,'Liadov','A Musical Snuff Box (waltz) Op. 32','Pops','Carl Fischer'),
    (628.0,'Liszt','Rakoczy March','Pops','Carl Fischer'),
    (322.0,'Liszt','Liebestraume','Pops','Carl Fischer'),
    (323.0,'Mascagni','Prelude & Siciliana Cavelleria Rusticana','Pops','Carl Fischer'),
    (505.0,'Moore','Pagent of Pt. Barnum Suite','Pops','Carl Fischer'),
    (398.0,'Orth','In the Clock Store','Pops','Carl Fischer'),
    (396.0,'Pryor','The Whistler & His Dog','Pops','Carl Fischer'),
    (278.0,'Rimsky-Korsakov','The Flight of the Bumble Bee','Pops','Carl Fischer'),
    (632.0,'Rubenstein','Melody in F','Pops','Carl Fischer'),
    (329.0,'SaintSaens','Danse Macabre op. 40','Pops','Carl Fischer'),
    (627.0,'SaintSaens','The Swan','Pops','Carl Fischer'),
    (630.0,'Seredy','Old Glory Selection','Pops','Carl Fischer'),
    (330.0,'Sibelius','Valse Triste','Pops','Carl Fischer'),
    (328.0,'Strauss','Pizzicato Polka and Arion Carnival march','Pops','Carl Fischer'),
    (619.0,'Strauss','Southern roses Waltz','Pops','Carl Fischer'),
    (333.0,'Strauss','Tales From the Vienna Woods op. 325','Pops','Carl Fischer'),
    (335.0,'Thomas','Entr''acte Gavotte Mignon','Pops','Carl Fischer'),
    (395.0,'Tchaikovsky','Sleeping Beauty Waltz','Pops','Carl Fischer'),
    (339.0,'VonWeber','Invitation to the Dance op. 65','Pops','Carl Fischer'),
    (399.0,'Waldteufel','The Skaters Waltz','Pops','Carl Fischer'),
    (334.0,'Wieniawski','Romance op.22','Pops','Carl Fischer'),
    (105.0,'Coates','Cinderella - Phantasy','Pops','Chappell'),
    (579.0,'Gould','Skier''s Waltz','Pops','Chappell'),
    (20.0,'Loewe','My Fair Lady','Pops','Chappell'),
    (1089.0,'Gillespie','Night in Tunisia','Pops','Crook'),
    (1101.0,'Zawinul','Birdland','Pops','Crook'),
    (1294.0,'Davis','Stille Nacth','Pops','Dots and Ink'),
    (13.0,'SaintSaens','Carnival of the Animals','Pops','Durand'),
    (1094.0,'Basie','One O''Clock Jump','Pops','Dwyer'),
    (1099.0,'Basie','Jumpin'' at the Woodside','Pops','Dwyer'),
    (1086.0,'Basie','Jumpin at the Woodside','Pops','Dwyer'),
    (1092.0,'Dwyer','Moten Swing','Pops','Dwyer'),
    (1098.0,'Ellington','Sophisticated Ladies: An Ellington Medley','Pops','Dwyer'),
    (1095.0,'Ellington','Night Train','Pops','Dwyer'),
    (1097.0,'Handy','St. Louis Blues','Pops','Dwyer'),
    (1105.0,'Herman','Woodchopper''s Ball','Pops','Dwyer'),
    (1100.0,'Sampson','Stompin at the Savoy','Pops','Dwyer'),
    (270.0,'White','Five Miniatures ofr Orchestra','Pops','Elkan Vogel'),
    (54.0,'Mancini','Mancini Memories','Pops','Famous'),
    (18.0,'Mancini','Moon River','Pops','Famous'),
    (618.0,'Tobani','The Sleeping Beauty','Pops','Carl Fischer'),
    (389.0,'Wilson','Romainian Gypsy Dances','Pops','Gamble'),
    (566.0,'Gershwin','Porgy and Bess','Pops','Gershwin'),
    (426.0,'Williams','Close Encounters of the Thrid Kind','Pops','Gold Horizon'),
    (1298.0,'Barry','Dances with Wolves','Pops','Hal Leonard'),
    (1252.0,'Beatles','Love Is All You Need (A Tribute to the Beatles)','Pops','Hal Leonard'),
    (1295.0,'Davis','Stille Nacht','Pops','Hal Leonard'),
    (908.0,'Herman','La Cage Auz Folles Selections','Pops','Hal Leonard'),
    (1004.0,'Horner','Titanic','Pops','Hal Leonard'),
    (53.0,'Lowden','Les Miserables Selections','Pops','Hal Leonard'),
    (573.0,'Schoenberg','Miss Saigon','Pops','Hal Leonard'),
    (52.0,'Schoenberg','I Dreamed a Dream (Les Miserables)','Pops','Hal Leonard'),
    (5.0,'Webber','The Music of the Night','Pops','Hal Leonard'),
    (23.0,'Webber','Selections from "Cats"','Pops','Hal Leonard'),
    (55.0,'Webber','Symphonic Reflections','Pops','Hal Leonard'),
    (51.0,'Webber','The Phantom of the Opera Selections','Pops','Hal Leonard'),
    (1290.0,'Williams','The Cowboys','Pops','Hal Leonard'),
    (1005.0,'Williams','Escapades for Alto Sax and Orchestra','Pops','Hal Leonard'),
    (1195.0,'Williams','Born on the Fourth of July','Pops','Hal Leonard'),
    (1300.0,'Zimmer','Pirates of the Caribbean: At World''s End','Pops','Hal Leonard'),
    (621.0,'Gade','Jalousie','Pops','Harms'),
    (584.0,'Gershwin','American in Paris','Pops','Harms'),
    (280.0,'Gershwin','The man I Love','Pops','Harms');
INSERT INTO "library" VALUES
    (624.0,'Rodgers','Carousel','Pops','Harms'),
    (413.0,'Romberg','A Tibute to Romberg','Pops','Harms'),
    (300.0,'Romberg','Sigmund Romverg Favorites','Pops','Harms'),
    (1103.0,'Dwyer','Kitty Litter Variations','Pops','Jerry Lackey'),
    (711.0,'Anderson','Chicken Reel','Pops','Kalmus'),
    (1117.0,'Anderson','Clarinet Candy','Pops','Kalmus'),
    (1136.0,'Anderson','Irish Suite (3,4,6)','Pops','Kalmus'),
    (1146.0,'Anderson','Belle of the Ball','Pops','Kalmus'),
    (1147.0,'Anderson','Sarabande','Pops','Kalmus'),
    (162.0,'Dvorak','Slavonic Dance op. 46 #1','Pops','Kalmus'),
    (11.0,'Fucik','Entrance of the Gladiators March','Pops','Kalmus'),
    (408.0,'Herbert','American Fantasy','Pops','Kalmus'),
    (535.0,'Prokofiev','Peter and the Wolf','Pops','Kalmus'),
    (38.0,'Ravel','Ma Mere L''Oye(Mother Goose) 5 pieces','Pops','Kalmus'),
    (200.0,'Sarasate','Zigeunerweisen','Pops','Kalmus'),
    (131.0,'Schreiner','The Worried Drummer','Pops','Kalmus'),
    (17.0,'Strauss','Blue Danube Waltz','Pops','Kalmus'),
    (276.0,'Strauss','Tales from the Vienna Woods op. 325','Pops','Kalmus'),
    (298.0,'Strauss','Voices of Spring op. 410 Waltz','Pops','Kalmus'),
    (360.0,'Strauss','Wiener Blut op.354 Waltz','Pops','Kalmus'),
    (1002.0,'Sullivan','Pirates of Penzance, With Catkile Tread','Pops','Kalmus'),
    (1056.0,'Beatles','Beatles Medley','Pops','Kalmus'),
    (132.0,'Strauss','Radetzsky March','Pops','Kalmus'),
    (522.0,'Strauss','Tritsch-Tratsch polka','Pops','Kalmus'),
    (1081.0,'Duke','April in Paris','Pops','Lackey'),
    (1079.0,'Ellington','C Jam Blues','Pops','Lackey'),
    (2.0,'Khatchaturian','Sabre Dance-Gayne Ballet','Pops','Leeds'),
    (425.0,'Webber','Jesus Christ Superstar','Pops','Leeds'),
    (114.0,'Liszt','2nd Hungarian Rhapsody','Pops','Lucks'),
    (1111.0,'Sousa','Hands Across the Sea','Pops','Lucks'),
    (232.0,'Strauss','Emperor Waltz Op. 437','Pops','Lucks'),
    (407.0,'Strauss','Centennial Waltz','Pops','Lucks'),
    (108.0,'Strauss','Czardas Die Fledermaus','Pops','Lucks'),
    (1018.0,'Sullivan','HMS Pinafore, We Sail The Ocean Blue','Pops','Lucks'),
    (1019.0,'Sullivan','HMS Pinafore, A British Tar','Pops','Lucks'),
    (1001.0,'Sullivan','Pirates of Penzance, I Am A Pirate King','Pops','Lucks'),
    (19.0,'Bocook','Movie Spectacular','Pops','Lucks'),
    (217.0,'Ernesto de Curtis','Come Back to Sorrento','Pops','Lucks'),
    (14.0,'Kabalevsky','The Comedians op.26','Pops','Lucks'),
    (424.0,'Beatles','Beatlemania for Strings','Pops','Maclen'),
    (15.0,'Dwyer','Sophisticated Ladies- Ellington Medley','Pops','Manuscript'),
    (472.0,'Lackey','Sgt. Peppers…with a little help','Pops','Manuscript'),
    (474.0,'Lackey','Latin Trilogy','Pops','Manuscript'),
    (209.0,'Joplin','The Sting','Pops','MCA'),
    (24.0,'Weber','"Evita" Highlights','Pops','MCA'),
    (151.0,'Anderson','Blue Tango','Pops','Belwin Mills'),
    (258.0,'Anderson','The Typewriter','Pops','Belwin Mills'),
    (259.0,'Anderson','The Syncopated Clock','Pops','Belwin Mills'),
    (385.0,'Anderson','Fiddle-Faddle','Pops','Belwin Mills'),
    (561.0,'Anderson','The Waltzing Cat','Pops','Belwin Mills'),
    (615.0,'Gould','Pavanne','Pops','Belwin Mills'),
    (435.0,'Joplin','The Easy Winners','Pops','Multimood'),
    (436.0,'Joplin','The Entertainer','Pops','Multimood'),
    (1296.0,'Holcombe','Twas the Night Before Christmas','Pops','Musicians Publications'),
    (382.0,'Shostakovich','The Golden Age Polka','Pops','Musicus'),
    (181.0,'Lai','A Man and A Woman','Pops','Northern'),
    (210.0,'Delius','Two Pieces for small orchestra: On Hearing the First Cuckoo in Spring and Summer Night on the River','Pops','Oxford'),
    (211.0,'Augustin','Granada','Pops','Peer International'),
    (292.0,'Rimsky-Korsakov','Themes form Scherezade','Pops','ProArt'),
    (378.0,'Grofe','On The Trail Grand Canyon Suite','Pops','Robbins'),
    (577.0,'Bernstein','Overture to Candide','Pops','Schirmer'),
    (373.0,'Bernstein','West Side Story Overture','Pops','Schirmer'),
    (393.0,'Brahms','Hungarian Dances #5, #6','Pops','Schirmer'),
    (631.0,'Dent','Juba (In The Bottoms)','Pops','Schirmer'),
    (350.0,'Dvorak','Slavic Dance #10 op. 72','Pops','Schirmer'),
    (342.0,'Grainger','Country Gardens','Pops','Schirmer'),
    (343.0,'Grainger','Molly on the Shore Irish Reel','Pops','Schirmer'),
    (557.0,'Herbert','Two pieces form Natoma','Pops','Schirmer'),
    (394.0,'Monti','Czardas','Pops','Schirmer'),
    (327.0,'Rimsky-Korsakov','Dance of the Buffoons','Pops','Schirmer'),
    (340.0,'WolfFerrari','Intermezzo Jewels of the Madonna','Pops','Schirmer'),
    (563.0,'Herbert','Badinage','Pops','Schuberth'),
    (651.0,'Honegger','Pacific 231','Pops','Senart'),
    (28.0,'Arnaud','Bugler''s Dream','Pops','Shawnee'),
    (1201.0,'Berlin','A Symphonic Portrait','Pops','Shawnee'),
    (30.0,'Zaninelli','Americana','Pops','Shawnee'),
    (1152.0,'Stllman','Home for the Holidays','Pops','Shawnee'),
    (70.0,'Menken','Beauty and the Beast','Pops','Walt Disney'),
    (668.0,'Webb','MacArthur Park','Pops','Warner Brothers'),
    (1106.0,'Bernard','Winter Wonderland','Pops','Warner Brothers'),
    (75.0,'Williams','Olympic Fanfare & Theme','Pops','Warner Tamerlane'),
    (1082.0,'May','Lean Baby','Pops','Wayland'),
    (1078.0,'Morton','King Porter Stomp','Pops','Wayland'),
    (164.0,'Rodgers','Oklahoma','Pops','Willamson'),
    (269.0,'Herbert','The Fortune Teller','Pops','Witmark'),
    (648.0,'Herbert','March of the Toys from Babes in Toyland','Pops','Witmark'),
    (564.0,'Herbert','Victor Herbert Favorites','Pops','Witmark'),
    (266.0,'Berlin','Easter Parade','Pops','Lucks'),
    (1139.0,'Casasanta','Notre Dame, Our Mother','Pops','Lucks'),
    (854.0,'Chase','The Muppet Medley','Pops','Lucks'),
    (857.0,'Chase','Broadway Tonight','Pops','Lucks'),
    (838.0,'Cohen','Star Spangled Spectacular','Pops','Lucks'),
    (788.0,'Cohen','Star Spangled Spectacular','Pops','Lucks'),
    (853.0,'Custer','Themes from 007','Pops','Lucks'),
    (934.0,'Custer','Beach Boys Medley','Pops','Lucks'),
    (1102.0,'Dwyer','Kitty Litter Variations','Pops','Lucks'),
    (849.0,'Dwyer','Ellington Rockn'' in Rhythm','Pops','Lucks'),
    (928.0,'Dwyer','Sweet Suite (2002)','Pops','Lucks'),
    (1084.0,'Dwyer','The Abha Kingdom','Pops','Lucks'),
    (947.0,'Dye','Notre Dame Victory March','Pops','Lucks'),
    (76.0,'Gershwin','Strike up the Band','Pops','Lucks'),
    (712.0,'Gould','Soft Shoe Gavotte','Pops','Lucks'),
    (1251.0,'Grechesky','Butler War Song','Pops','Lucks'),
    (504.0,'Grofe','Mississippi Suite','Pops','Lucks'),
    (886.0,'Horner','My Heart Will Go On (Titanic)','Pops','Lucks'),
    (884.0,'Hupfeld','As Time Goes By','Pops','Lucks'),
    (1268.0,'Lackey','Irish Dance','Pops','Lucks'),
    (850.0,'Lackey','Songs Sinatra Sang','Pops','Lucks'),
    (1088.0,'Lackey','Pizzazzy Fanfares','Pops','Lucks'),
    (248.0,'Lehigh','Man of La Mancha','Pops','Lucks'),
    (714.0,'Liadov','Baba-Jaga op 56','Pops','Lucks'),
    (837.0,'Meacham','American Patrol','Pops','Lucks'),
    (816.0,'Mendelsshon','Wedding March Op.61 No. 9','Pops','Lucks'),
    (1093.0,'Monk','Round Midnight','Pops','Lucks'),
    (860.0,'Proto','Casey At the Bat','Pops','Lucks'),
    (790.0,'Richardson','Star Spangled Banner','Pops','Lucks'),
    (914.0,'Rimsky-Korsakov','Flight of The Bumble Bee','Pops','Lucks'),
    (745.0,'Rodgers','The Sound of Music','Pops','Lucks'),
    (390.0,'Rodgers','South Pacific','Pops','Lucks'),
    (264.0,'Rogers','The King and I','Pops','Lucks'),
    (625.0,'Rose','Waukegan Concerto','Pops','Lucks'),
    (713.0,'Rosenhaus','The Wind Beneath My Wings','Pops','Lucks'),
    (1130.0,'Shea','Notre Dame Victory March','Pops','Lucks'),
    (841.0,'Silvestri','Forest Gump Suite','Pops','Lucks'),
    (787.0,'Sousa','The Thunderer March','Pops','Lucks'),
    (836.0,'Sousa','The Gliding Girl Tango','Pops','Lucks'),
    (839.0,'Sousa','Presidential Polonaise','Pops','Lucks'),
    (840.0,'Sousa','Hail to The Spirit of Liberty','Pops','Lucks'),
    (799.0,'Sullivan','Pirates od Penzance','Pops','Lucks'),
    (1104.0,'Wayland','Tidy-Cat 3','Pops','Lucks'),
    (885.0,'Weber','Memory from Cats','Pops','Lucks'),
    (804.0,'Weill','Mack the Knife','Pops','Lucks'),
    (859.0,'Williams','Hymn to the Fallen','Pops','Lucks'),
    (954.0,'Williams','Across The Stars','Pops','Lucks'),
    (803.0,'Williams','Summon The Heros','Pops','Lucks'),
    (795.0,'Williams','Adventures on Earth','Pops','Lucks'),
    (796.0,'Williams','Empire Strikes Back Medly','Pops','Lucks'),
    (878.0,'Williams','Star Wars Phantom Menace Suite','Pops','Lucks'),
    (935.0,'Williams','The Cowboys Overture','Pops','Lucks'),
    (944.0,'Williams','The Patriot','Pops','Lucks'),
    (951.0,'Williams','Adventures On Earth (from E.T.)','Pops','Lucks'),
    (956.0,'Williams','Liberty Fanfare','Pops','Lucks'),
    (957.0,'Williams','Star Wars','Pops','Lucks'),
    (958.0,'Williams','Three Pieces form Schindler''s List','Pops','Lucks'),
    (967.0,'Williams','Harry Potter and The Socerer''s Stone','Pops','Lucks'),
    (967.0,'Williams','Harry Potter and The Socerer''s Stone','Pops','Lucks'),
    (969.0,'Williams','Hymn to The Fallen','Pops','Lucks'),
    (991.0,'Williams','Suite from J.F.K.','Pops','Lucks'),
    (953.0,'Williams','Raiders March','Pops','Lucks'),
    (716.0,'Williams','Jurasic Park','Pops','Lucks'),
    (855.0,'Williams','Star Trek Through The Years','Pops','Lucks'),
    (852.0,'Williams','Star Wars Main Theme','Pops','Lucks'),
    (1012.0,'Berlin','God Bless America','Patriotic','Lucks'),
    (921.0,'Wolf','Italian Serenade','Small Ensemble','Lucks'),
    (8.0,'Schubert','Octet in F op 166','Small Ensemble','Baerenreiter'),
    (1061.0,'Dvorak','String Quartet No.12 in F major, Op.96','Small Ensemble','Baerenreiter'),
    (1033.0,'Mozart','Quartet for Flute','Small Ensemble','Baerenreiter'),
    (1036.0,'Mozart','Serenade in C','Small Ensemble','Baerenreiter'),
    (1021.0,'Mozart','Serenade in e min. KV388','Small Ensemble','Baerenreiter'),
    (140.0,'Matesky','Odyssey in Strings Vol. 1','Small Ensemble','Belwin Mills'),
    (152.0,'Dukas','Fanare "La Peri"','Small Ensemble','Durand'),
    (586.0,'Shostakovich','Prelude','Small Ensemble','Edition Musicus'),
    (178.0,'Rouse','Ogoun Badagris Percussion Ensemble','Small Ensemble','Helicon'),
    (1156.0,'Beethoven','String Quartet Op. 135 in F major','Small Ensemble','Henle'),
    (189.0,'Dvorak','Quintet op.77','Small Ensemble','International'),
    (946.0,'Faure','Quartet','Small Ensemble','International'),
    (587.0,'Schoenberg','Verklaerte Nacht','Small Ensemble','International'),
    (190.0,'Vivaldi','3 Quartets','Small Ensemble','International'),
    (142.0,'Stravinsky','Histoire du Soldat','Small Ensemble','Kalmus'),
    (120.0,'Tchaikovsky','Serenade','Small Ensemble','Kalmus'),
    (473.0,'Martinu','La Revue De Cuisine','Small Ensemble','Leduc'),
    (188.0,'Spohr','Nonet','Small Ensemble','Litolf'),
    (1068.0,'Tartini','Violin Sonata in g minor','Small Ensemble','Lucks'),
    (471.0,'Deak','Lucy & the Couont (Lovedreams from Transyvania)','Small Ensemble','Manuscript'),
    (362.0,'Gabrieli','Canzoni #27,#28','Small Ensemble','Musica Rara'),
    (185.0,'Mozart','Don Giovanni vol. 1 Melodies','Small Ensemble','Musica Rara'),
    (186.0,'Mozart','Don Giovanni vol. 2 Melodies','Small Ensemble','Musica Rara'),
    (473.0,'Martinu','La Revue De Cuisine','Small Ensemble','Musicales Alphonse Leduc'),
    (116.0,'Sousa','Stars and Stripes Forever','Small Ensemble','Musicians Publications'),
    (77.0,'Gershwin','Lullaby','Small Ensemble','New World'),
    (813.0,'Mozart','String Quartet Collection','Small Ensemble','Peters'),
    (581.0,'Spohr','Grand Nonetto op.31','Small Ensemble','Peters'),
    (29.0,'Poulenc','Sextet','Small Ensemble','Petrucci'),
    (945.0,'Barber','String Quartet','Small Ensemble','Schirmer'),
    (7.0,'Hindemith','Kleine Kammermusik','Small Ensemble','Schott'),
    (960.0,'Pachelbel','Canon for Strings','Small Ensemble','Schott'),
    (125.0,'Weill','Little Threepenny Music','Small Ensemble','Universal'),
    (118.0,'Tchaikovsky','Nutcracker Suite Selections','Small Ensemble','WB Music'),
    (848.0,'Beethoven','String Quartets Opus 18 Nos. 1-6','Small Ensemble','Lucks'),
    (880.0,'Beethoven','String Quartet op.59,74,95','Small Ensemble','Lucks'),
    (972.0,'Beethoven','Octet','Small Ensemble','Lucks'),
    (683.0,'Boccherini','Bird Sanctuary Quintet','Small Ensemble','Lucks'),
    (755.0,'Borodin','Quartet No. 2 in D Major','Small Ensemble','Lucks'),
    (812.0,'Borodin','Quartet #2 D Major','Small Ensemble','Lucks'),
    (682.0,'Carter','String Quartet No. 1 (1951)','Small Ensemble','Lucks'),
    (771.0,'Chopin','Victorian Trombone Mass','Small Ensemble','Lucks'),
    (896.0,'Debussy','Danses (Sacred & Profane) ?','Small Ensemble','Lucks'),
    (684.0,'Dvorak','Quintet in G maj. Op. 77','Small Ensemble','Lucks'),
    (931.0,'Elgar','Introduction and Allegro op. 47','Small Ensemble','Lucks'),
    (883.0,'Gershwin','Prelude No. 2 Piano','Small Ensemble','Lucks'),
    (930.0,'Grieg','Two Norwegian Airs for Strings','Small Ensemble','Lucks'),
    (965.0,'Handel','Concerto Grosso in b minor No.12','Small Ensemble','Lucks'),
    (750.0,'Ibert','Deux Movements','Small Ensemble','Lucks'),
    (882.0,'Joplin','Ragtime Favorites for Strings','Small Ensemble','Lucks'),
    (646.0,'Lauber','Four Danses Medievales','Small Ensemble','Lucks'),
    (809.0,'Mendelsshon','Octet','Small Ensemble','Lucks'),
    (808.0,'Milhaud','Sympnonies for small Orchestra','Small Ensemble','Lucks'),
    (775.0,'Mozart','Serenade No. 12 "Nacht Musique" c min. KV.','Small Ensemble','Lucks'),
    (890.0,'Mozart','Sinfonia Concertante in Eb major KV. 2976','Small Ensemble','Lucks'),
    (910.0,'Mozart','Divertimento (Trio) Eb major KV. 563','Small Ensemble','Lucks'),
    (932.0,'Mozart','Serenade in D major KV 239','Small Ensemble','Lucks'),
    (71.0,'North','Unchained melody','Small Ensemble','Lucks'),
    (702.0,'Poulenc','Sonata for Horn, Trumpet & Trombone','Small Ensemble','Lucks'),
    (778.0,'Prokofiev','Quintet op.39','Small Ensemble','Lucks'),
    (920.0,'Puccini','Crisantini','Small Ensemble','Lucks'),
    (950.0,'Ravel','Introduction and Allegro','Small Ensemble','Lucks'),
    (894.0,'SaintSaens','Septet op. 65','Small Ensemble','Lucks'),
    (756.0,'Scarlatti','Su Le Sponde Del Tebro','Small Ensemble','Lucks'),
    (810.0,'Shostakovich','Chamber Symphony op.110a','Small Ensemble','Lucks'),
    (891.0,'Strauss','Serenade op. 7','Small Ensemble','Lucks'),
    (691.0,'Stravinsky','Symphony of Wind Instruments','Small Ensemble','Lucks'),
    (751.0,'Tchaikovsky','Humoresque (wind Quartet)','Small Ensemble','Lucks'),
    (990.0,'Warlock','Capriol Suite for String orchestra','Small Ensemble','Lucks'),
    (1207.0,'Mozart','Nehmt meinen Dank, ihr holden Gonner!','Opera','Lucks'),
    (1208.0,'Mozart','Porgi, amor, qualche ristoro from The Marriage of Figaro','Opera','Lucks'),
    (1209.0,'Mozart','Vado, ma dove? K. 583','Opera','Lucks'),
    (299.0,'Anderson','Plink, Plank Plunk','String Orchestra','Belwin Mills'),
    (219.0,'Cowell','Fiddler''s Jig','String Orchestra','Associated'),
    (41.0,'Mozart','Eine Kleine Nachtmusik KV 525','String Orchestra','Baerenreiter'),
    (612.0,'Boccherini','Celebrated Minuet','String Orchestra','Boosey and Hawkes'),
    (216.0,'Elgar','Serenade op.20','String Orchestra','Lucks'),
    (554.0,'Bloch','Concerto Grosso','String Orchestra','Broude Brothers'),
    (153.0,'Bach','Air','String Orchestra','Carl Fischer'),
    (326.0,'Raff','The Mill (from string quartet op.192 #2)','String Orchestra','Carl Fischer'),
    (91.0,'Roussel','Sinfonietta','String Orchestra','Durand'),
    (366.0,'Diamond','Rounds','String Orchestra','Elkan Vogel'),
    (220.0,'Billings','America','String Orchestra','Penny'),
    (63.0,'Arensky','Variation on a theme by Tchaikovsky','String Orchestra','Kalmus'),
    (275.0,'Bach','Concerto in G Bradenburg No.3','String Orchestra','Kalmus'),
    (272.0,'Corelli','Concerto Grosso op.6 #8 (christmas)','String Orchestra','Kalmus'),
    (509.0,'Grieg','In Olden Style suite op. 40','String Orchestra','Kalmus'),
    (170.0,'Grieg','Suite in Olden Syle Holberg op.40','String Orchestra','Kalmus'),
    (622.0,'Grieg','Heart Wounds','String Orchestra','Kalmus'),
    (622.0,'Grieg','Last Spring','String Orchestra','Kalmus'),
    (143.0,'Mahler','Adagietto','String Orchestra','Kalmus'),
    (48.0,'Sibelius','Romance in C op.42','String Orchestra','Kalmus'),
    (49.0,'Sibelius','Canzonetta op.62a','String Orchestra','Kalmus'),
    (72.0,'Vivaldi','The Four Seasons op. 8 #4 Winter','String Orchestra','Kalmus'),
    (145.0,'Vivaldi','The Four Seasons Autumn','String Orchestra','Kalmus'),
    (1008.0,'Rossini','Sonata No. 1','String Orchestra','Lucks');
INSERT INTO "library" VALUES
    (146.0,'Vivaldi','The Four Seasons Spring','String Orchestra','Lucks'),
    (239.0,'Arensky','Variations on a Theme by Tchaikovsky','String Orchestra','Lucks'),
    (199.0,'Corelli','Suite for Srtings','String Orchestra','Manuscript'),
    (122.0,'Ravel','Meditation','String Orchestra','Manuscript'),
    (231.0,'Bach','Jesu Joy of Man''s Desiring','String Orchestra','Oxford'),
    (367.0,'Britten','Simple Symphony','String Orchestra','Oxford'),
    (649.0,'VaughanWilliams','Dives and Lazarus','String Orchestra','Oxford'),
    (433.0,'Walton','Two Pieces for Strings Henry V','String Orchestra','Oxford'),
    (518.0,'Barber','Adagio for Strings','String Orchestra','Schirmer'),
    (598.0,'VaughanWilliams','Fantasia on a Theme by Thomas Tallis','String Orchestra','Schirmer'),
    (401.0,'Bolozoni','Minuetto','String Orchestra','Lucks'),
    (588.0,'Bach','Prelude and Toccata','String Orchestra','Wiltark'),
    (673.0,'Borodin','Nocturne','String Orchestra','Boosey and Hawkes'),
    (1239.0,'Glazunov','Chopiniana, Op. 46','Orchestra','Lucks'),
    (895.0,'Franck','Symphonic Variations for Piano and Orchestra','Orchestra','Lucks'),
    (1265.0,'Gounod','Romeo and Juliet: Waltz Song: Ah! Je Veux Vivre! (F Major)','Opera','Lucks'),
    (1266.0,'Gounod','Romeo and Juliet: L''amour! Oui, son ardeur/Ah! Leve-toi soleil! (Bb Maj parts, score only available in B Maj)','Opera','Lucks'),
    (1267.0,'Gounod','Romeo and Juliet: Nuit d''hymenee (Chamber Scene)','Opera','Lucks'),
    (537.0,'Beethoven','Symphony No.3 (Eroica) op. 55','Orchestra','Associated'),
    (661.0,'Beethoven','Symphony No.3 Eroica','Orchestra','Associated'),
    (543.0,'Bizet','Symphony No.1 in C','Orchestra','Associated'),
    (101.0,'Dvorak','Symphony No.2 in D minor op. 70','Orchestra','Associated'),
    (84.0,'Mozart','Symphony No.41 Jupiter','Orchestra','Baerenreiter'),
    (1191.0,'Mozart','Symphony No.4 in D Major, KV 19','Orchestra','Baerenreiter'),
    (846.0,'Beethoven','Symphony No.2','Orchestra','Baerenreiter'),
    (942.0,'Beethoven','Symphony No.7','Orchestra','Baerenreiter'),
    (1180.0,'Beethoven','Symphony No.8 op. 93','Orchestra','Baerenreiter'),
    (1271.0,'Beethoven','Concerto in C Major, Op. 56 "Triple Concerto"','Orchestra','Baerenreiter'),
    (996.0,'Beethoven','Symphony No.1 in C Major','Orchestra','Baerenreiter'),
    (1003.0,'Beethoven','Symphony No.6','Orchestra','Baerenreiter'),
    (1035.0,'Mozart','Symphony No.35 "Haffner" K385','Orchestra','Baerenreiter'),
    (1022.0,'Mozart','Symphony No.31, "Paris" in D Major','Orchestra','Baerenreiter'),
    (1282.0,'Mozart','Symphony in A Major, no. 29, KV201','Orchestra','Baerenreiter'),
    (1303.0,'Schubert','Symphony in D, no. 1, D 82','Orchestra','Baerenreiter'),
    (1116.0,'Schubert','Symphony No. 3, D.200','Orchestra','Baerenreiter'),
    (831.0,'Beethoven','Symphony No.3','Orchestra','Baerenreiter'),
    (1058.0,'Berlioz','Symphonie Fantastique op.14','Orchestra','Baerenreiter'),
    (869.0,'Beethoven','Symphony No.9 d min op. 125','Orchestra','Baerenreiter'),
    (870.0,'Mozart','Sinfonie in C KV. 338','Orchestra','Baerenreiter'),
    (549.0,'Haydn','Symphony No.92 in G','Orchestra','Boosey and Hawkes'),
    (545.0,'Haydn','Symphony No.45 (Farewell)','Orchestra','Boosey and Hawkes'),
    (314.0,'Beethoven','Symphony No.7','Orchestra','Breitkopf'),
    (104.0,'Haydn','Symphony No.104 the London','Orchestra','Breitkopf'),
    (440.0,'Mozart','Symphony No.36 in C KV. 425','Orchestra','Breitkopf'),
    (237.0,'Brahms','Symphony No.1 op.68','Orchestra','Breitkopf'),
    (548.0,'Brahms','Symphony No.4 in e minor Op. 98','Orchestra','Breitkopf'),
    (94.0,'Brahms','Symphony No.3 op. 90','Orchestra','Breitkopf'),
    (102.0,'Haydn','Symphony No.101 The Clock','Orchestra','Breitkopf'),
    (412.0,'Mendelsshon','Symphony No.3 op. 56','Orchestra','Breitkopf'),
    (26.0,'Mendelsshon','Symphony No.4 op. 90','Orchestra','Breitkopf'),
    (83.0,'Mozart','Symphony No.41 Jupiter','Orchestra','Breitkopf'),
    (99.0,'Schumann','Symphony No.1 in Bb op.38','Orchestra','Breitkopf'),
    (475.0,'Schumann','Symphony No.3 inE op.97','Orchestra','Breitkopf'),
    (100.0,'Tchaikovsky','Symphony No.6 in B minor Pathetique op. 74','Orchestra','Breitkopf'),
    (364.0,'Beethoven','Symphony No.6 in F op. 68','Orchestra','Breitkopf'),
    (409.0,'Schubert','Symphony No.7 In C','Orchestra','Breitkopf'),
    (256.0,'Beethoven','Symphony No.8 op. 93','Orchestra','Broude Brothers'),
    (544.0,'Schubert','Symphony No.8 in b minor, Unfinished','Orchestra','Broude Brothers'),
    (80.0,'Beethoven','Symphony No.5','Orchestra','Broude Brothers'),
    (92.0,'Mendelsshon','Symphony No.5, Reformation','Orchestra','Broude Brothers'),
    (605.0,'Beethoven','Symphony No.1 in C op. 21','Orchestra','Carl Fischer'),
    (81.0,'Beethoven','Symphony No.6','Orchestra','Carl Fischer'),
    (6.0,'Schubert','Symphony No.8 in b minor, Unfinshed','Orchestra','Carl Fischer'),
    (835.0,'Dvorak','Symphony No.9 E minor','Orchestra','Sourer'),
    (1027.0,'Haydn','Symphony No.1','Orchestra','Doblinger'),
    (282.0,'Haydn','Symphony No.30','Orchestra','Doblinger'),
    (419.0,'Mozart','Symphony No.35, Haffner','Orchestra','Hampton'),
    (550.0,'Beethoven','Symphony No.7 op. 92','Orchestra','Hampton'),
    (546.0,'Brahms','Symphony No.2 op. 73','Orchestra','Hampton'),
    (547.0,'Prokofiev','Classical Symphony )p. 25','Orchestra','Hampton'),
    (113.0,'Haydn','Symphony No.100 Military','Orchestra','Haydn Mozart Press'),
    (361.0,'Haydn','Symphony No.104, London','Orchestra','Haydn Mozart Press'),
    (33.0,'Beethoven','Symphony No.6 op.68','Orchestra','Kalmus'),
    (80.0,'Beethoven','Symphony No.5 op. 67','Orchestra','Kalmus'),
    (144.0,'Beethoven','Symphony No.2','Orchestra','Kalmus'),
    (637.0,'Beethoven','Symphony No.3 op. 55','Orchestra','Kalmus'),
    (638.0,'Beethoven','Symphony No.4 op.60','Orchestra','Kalmus'),
    (363.0,'Cherubini','Sinfonia in D','Orchestra','Kalmus'),
    (27.0,'Dvorak','Symphony No.5 From The New World','Orchestra','Kalmus'),
    (647.0,'Dvorak','Symphony No.8 op.88','Orchestra','Kalmus'),
    (107.0,'Dvorak','Symphony No.6 op.60','Orchestra','Kalmus'),
    (82.0,'Franck','Symphony in D minor','Orchestra','Kalmus'),
    (103.0,'Haydn','Symphony No.104 the London','Orchestra','Kalmus'),
    (98.0,'Haydn','Symphony No.95 in C Minor','Orchestra','Kalmus'),
    (93.0,'Haydn','Symphony No.100 Military','Orchestra','Kalmus'),
    (96.0,'Mozart','Symphony No.38 in D Prague KV. 504','Orchestra','Kalmus'),
    (234.0,'Mozart','Symphony No.1','Orchestra','Kalmus'),
    (439.0,'Mozart','Symphony No.39 in Eb Kv 543','Orchestra','Kalmus'),
    (154.0,'Prokoviev','Symphony No.5 op. 100','Orchestra','Kalmus'),
    (1140.0,'Salieri','Symphony in D, Sinfonia Veneziana','Orchestra','Kalmus'),
    (310.0,'Schubert','Symphony No.2','Orchestra','Kalmus'),
    (97.0,'Schubert','Symphony No.5 in Bb','Orchestra','Kalmus'),
    (659.0,'Schumann','Symphony No.3 Op.120','Orchestra','Kalmus'),
    (39.0,'Shostakovich','Symphony No.10','Orchestra','Kalmus'),
    (1174.0,'Strauss','Concerto No. 1 for Horn and Orchestra in E-flat, Op. 11','Orchestra','Kalmus'),
    (1222.0,'Tchaikovsky','Variations on a Rococo Theme','Orchestra','Kalmus'),
    (311.0,'Tchaikovsky','Symphony No.5','Orchestra','Kalmus'),
    (376.0,'Bach','Symphony No.3','Orchestra','Lucks'),
    (1217.0,'Beethoven','Ritterballet','Orchestra','Lucks'),
    (1215.0,'Brahms','Hungarian Dances #1,3,10','Orchestra','Lucks'),
    (1247.0,'Debussy','Clair de Lune','Orchestra','Lucks'),
    (1190.0,'Dvorak','Symphony No. 7','Orchestra','Lucks'),
    (1218.0,'Dvorak','Serenade for Strings Op. 22 in E Major','Orchestra','Lucks'),
    (1219.0,'Dvorak','Legends Op. 59, no. 1-5','Orchestra','Lucks'),
    (1244.0,'Dvorak','Legends, Op. 59, no. 6-10','Orchestra','Lucks'),
    (1007.0,'Franck','Symphony in d minor','Orchestra','Lucks'),
    (995.0,'Haydn','Symphony No.1','Orchestra','Lucks'),
    (1223.0,'Mahler','Symphony No. 4','Orchestra','Lucks'),
    (1184.0,'Massenet','Meditation from Thais','Orchestra','Lucks'),
    (1155.0,'Mendelsshon','Symphony No.1','Orchestra','Lucks'),
    (1250.0,'Puccini','La Boheme Fantasie','Orchestra','Lucks'),
    (1182.0,'SaintSaens','Symphony No, 2 in A minor, OP. 55','Orchestra','Lucks'),
    (1196.0,'SaintSaens','Suite for Orchestra, Op. 49','Orchestra','Lucks'),
    (1173.0,'Schumann','Symphony No. 2 in C Major, Op. 61','Orchestra','Lucks'),
    (1053.0,'Sibelius','Symphony in e minor','Orchestra','Lucks'),
    (1216.0,'Sibelius','Lemminkainen''s Return Op. 22 no. 4','Orchestra','Lucks'),
    (1232.0,'Sibelius','Symphony No. 5 in E-flat Major, Op. 82','Orchestra','Lucks'),
    (1076.0,'Tchaikovsky','Symphony No. 3 op.29','Orchestra','Lucks'),
    (1171.0,'Tchaikovsky','Pezzo Capriccioso. Op. 62','Orchestra','Lucks'),
    (95.0,'Berlioz','Symphonie Fantastique op.14','Orchestra','Lucks'),
    (1034.0,'Tchaikovsky','Symphony No 1','Orchestra','Lucks'),
    (1228.0,'Tchaikovsky','Symphony No.4','Orchestra','Lucks'),
    (660.0,'Beethoven','10th Symphony (from Quintet)','Orchestra','Papach'),
    (1177.0,'Brahms','Ein Deutsches Requiem Op. 45 (A German Requiem)','Orchestra','Peters'),
    (233.0,'Dittersdorf','Symphony in F','Orchestra','Schirmer'),
    (889.0,'Beethoven','Symphony No.2','Orchestra','Urtext'),
    (822.0,'Bach','Symphony in D major','Orchestra','Lucks'),
    (688.0,'Beethoven','Symphony No.1','Orchestra','Lucks'),
    (800.0,'Beethoven','Symphony No.4 in Bb','Orchestra','Lucks'),
    (984.0,'Borodin','Symophony No.2','Orchestra','Lucks'),
    (798.0,'Dvorak','Symphony No.4 in d minor op. 13','Orchestra','Lucks'),
    (941.0,'Dvorak','Symphomy No.8 G major op.88','Orchestra','Lucks'),
    (701.0,'Gounod','Petite Symphony','Orchestra','Lucks'),
    (12.0,'Haydn','Sinfonia #82','Orchestra','Lucks'),
    (679.0,'Haydn','Symphony No.49','Orchestra','Lucks'),
    (975.0,'Haydn','Sinfonia #103 "Drum Roll"','Orchestra','Lucks'),
    (1257.0,'Haydn','Symphony No. 45 "Farewell"','Orchestra','Lucks'),
    (1270.0,'Lacket','Coro di Zingari (Anvil Chorus from Il Trovatore)','Orchestra','Lucks'),
    (1225.0,'Lackey','Beethoven 9 last movement','Orchestra','Lucks'),
    (1269.0,'Lackey','Celebration 150','Orchestra','Lucks'),
    (815.0,'Lalo','Symphony Espagnole','Orchestra','Lucks'),
    (569.0,'Mozart','Paris Symphony in D KV. 297','Orchestra','Lucks'),
    (943.0,'Mozart','Symphony No.40 KV. 550 in g minor','Orchestra','Lucks'),
    (968.0,'Mozart','Symphony No.40 in g minor','Orchestra','Lucks'),
    (1066.0,'Mozart','Symphony #39 in Eb major, K.543','Orchestra','Lucks'),
    (801.0,'Rachmaninoff','Symphony No.2 op 27','Orchestra','Lucks'),
    (774.0,'Rodriquez','A Colorful Symphony','Orchestra','Lucks'),
    (782.0,'SaintSaens','Symphony No.3 "Organ"','Orchestra','Lucks'),
    (842.0,'Schubert','Symphony No.5 D485 in Bb Major','Orchestra','Lucks'),
    (949.0,'Schubert','Symphony No.2 in Bb major','Orchestra','Lucks'),
    (963.0,'Tchaikovsky','Symphony No.2','Orchestra','Lucks'),
    (858.0,'Weber','Symphonic Reflections','Orchestra','Lucks'),
    (793.0,'Dvorak','Symphony No.4 d minor','Orchestra','Lucks'),
    (1213.0,'Sarasate','Navarra Op. 33','Concerto','Lucks'),
    (1214.0,'Vieuxtemps','Fantasie Caprice Op. 11','Concerto','Lucks'),
    (1220.0,'Britten','War Requiem','Orchestra','Boosey and Hawkes'),
    (191.0,'Bach','Sheep May Safely Graze','Small Ensemble','Lucks'),
    (1285.0,'Wilhousky','Battle Hymn of the Republic','Orchestra','Carl Fischer'),
    (1256.0,'Bach','Ave Maria in F Major','Orchestra','Kalmus'),
    (1278.0,'Coleridge Taylor','Danse Negre','Orchestra','Lucks'),
    (1229.0,'De Falla','The Three Cornered Hat, Scenes and Dances from Part I','Orchestra','Lucks'),
    (1276.0,'Sousa','Gladiator March','Orchestra','Lucks'),
    (1179.0,'Wieniawski','Polonaise Brilliante, Op. 4, No. 1 in D Major','Orchestra','Lucks'),
    (1286.0,'WolfFerrari','Chamber Symphony, op. 8','Orchestra','Lucks'),
    (1284.0,'Carter','Lift Every Voice and Sing','Orchestra','Marvel'),
    (1170.0,'Gliere','Russian Sailors Dance from the Red Poppy','String Orchestra','Schirmer'),
    (1287.0,'Brown','We Shall Overcome','Orchestra','Uzze Brown'),
    (1254.0,'Bizet','Carmen Fantasy for Violin and Orchestra, Op. 25','Orchestra','Lucks'),
    (1255.0,'Brahms','Concerto No. 2 in B-flat Major for Piano and Orchestra, Op. 83','Orchestra','Lucks'),
    (1258.0,'Bruch','Violin Concerto No. 1 in g minor, Op. 26','Orchestra','Lucks'),
    (1277.0,'Lackey','Overture to William Tell','Orchestra','Lucks'),
    (757.0,'Reger','Marie Wegenied','Orchestra','Lucks'),
    (939.0,'Schubert','Missa in G','Orchestra','Lucks'),
    (1273.0,'Tchaikovsky','Nutcracker March','Orchestra','Lucks'),
    (1274.0,'Tchaikovsky','Nutcracker Sugar Plum Fairy','Orchestra','Lucks'),
    (1275.0,'Tchaikovsky','Nutcracker Trepak','Orchestra','Lucks');
